### ISSUE TITLE
程式碼區塊問題

### ISSUE THREAD

**Issue by YuDong-0222** [EvanNotFound/hexo-theme-redefine#10]
作者您好！您的主題非常優秀且美觀
我有個問題是關於「程式碼區塊」的樣式
我設置了mac 但沒有辦法顯示跟您的一樣

![5956EA67-7D0D-41D6-B585-98303025FDD7](https://user-images.githubusercontent.com/71540131/200719795-e840e270-45f0-44e6-99d6-b72cd5a4972d.jpeg)
如圖。

**Comment by EvanNotFound** [comment]
請把網址發給我，謝謝，我看一下控制台信息

**Comment by EvanNotFound** [comment]
请把你的 `主题自带配置文件 _config.yml` 和你的 `_config.redefine.yml` 全部发出来（敏感信息可删除）

**Comment by YuDong-0222** [comment]
> 请先执行
> 
> ```shell
> hexo clean
> ```
> 
> 测试一下，看看问题是否解决。如没解决，请继续提供以下信息
> 
> * 你的 `主题自带配置文件 _config.yml`
> * 你的 `_config.redefine.yml`（敏感信息可删除）
> * Hexo 版本
> * Node.js版本
> 
> 感谢

作者您好，問題已經解決。
我翻閱了先前的issue紀錄。
我將_config.yml 的 highlight 選項設置成該樣式就正常了！
`highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
`
