### ISSUE TITLE
[BUG] 文章并没有按照sticky属性大小进行排列

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#105]
**提交前检查单**
- [已经尝试执行 `hexo clean`，问题仍然存在]
- [已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/docs/quick-start/update)] 
- [已经确认同步了主题配置文件] 

**Bug 描述**
在文章的Front Matter中按照帮助文档中所说设置了sticky属性，但是发现实际上文章并没有按照sticky属性大小进行排列，而是按照文章发布时间进行排序的.
- hexo 根目录的网站配置文件 `_config.yml` [_config.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/11040792/_config.txt)
- 主题配置文件 `_config.redefine.yml` [_config.redefine.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/11040799/_config.redefine.txt)

**复现方法**
复现该 Bug 的步骤：
- 添加多个sticky值不同的文章
- 进入博客首页

**预期结果**
按sticky属性大小顺序进行排列显示

**截图**
无

**电脑：**
 - 操作系统：[Windows 10]
 - 浏览器 [Edge]
 - 版本 [ 111.0.1661.44]

**移动端：**
 - 设备：[例如 Radmi K40 Gaming]
 - 操作系统：[MIUI 12.5.8]
 - 浏览器 [夸克]
 - 版本 [6.2.0.245]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
你好，经过我的测试，`sticky` 按照数字大小进行排序是没问题的。无论是多少篇文章，都可以通过sticky值的大小进行排序。



<img width="1183" alt="Screenshot 2023-03-25 at 10 27 30 AM" src="https://user-images.githubusercontent.com/68590232/227723513-6dfafd37-07f5-4770-bd4c-0793be1db30c.png">
<img width="1123" alt="Screenshot 2023-03-25 at 10 28 05 AM" src="https://user-images.githubusercontent.com/68590232/227723518-36baeff0-ac56-4248-838c-12c5f6099b56.png">
<img width="1165" alt="Screenshot 2023-03-25 at 10 28 21 AM" src="https://user-images.githubusercontent.com/68590232/227723520-c4009973-8f24-40dc-a88d-5820265c0064.png">
<img width="1096" alt="Screenshot 2023-03-25 at 10 28 54 AM" src="https://user-images.githubusercontent.com/68590232/227723522-03654423-d08f-443a-8d5e-5e008e8ae12c.png">

**Comment by rygdsddssd** [comment]
谢谢，非常愚蠢的错误，我将sticky设置成了stick，十分抱歉，谢谢

从 Windows 版邮件发送

发件人: Evan Luo
发送时间: 2023年3月25日 22:31
收件人: EvanNotFound/hexo-theme-redefine
抄送: rygdsddssd; Author
主题: Re: [EvanNotFound/hexo-theme-redefine] [BUG] 文章并没有按照sticky属性大小进行排列 (Issue #105)

你好，经过我的测试，sticky 按照数字大小进行排序是没问题的。无论是多少篇文章，都可以通过sticky值的大小进行排序。
