### ISSUE TITLE
[功能建议] 折叠模块优化版式

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#107]
# **问题概述**
## 折叠模块作次级标题
当我想使用折叠模块作为标题时，右侧目录会将折叠模块内的文本也一并作标题
## 折叠模块内部标题及内容
折叠模块内想放入次级标题，这时文本格式出错
# **需求概述**
## 模块内部标题及内容格式的优化
# **图片描述**
![1](https://user-images.githubusercontent.com/86097988/227786628-f6bd1f07-cc56-4e25-9dc3-42560632f913.png)
![2](https://user-images.githubusercontent.com/86097988/227786635-9d1602dd-d259-4c36-bdce-4d3eca449504.png)
![3](https://user-images.githubusercontent.com/86097988/227786798-5dc6c8cd-4363-4658-8b30-bfcd64981b39.png)

**Comment by EvanNotFound** [comment]
好的，我看看

**Comment by EvanNotFound** [comment]
对于 Folding 模块作为标题，由于 Hexo 本身 Helpers 的渲染的限制，目前我还无法解决。

所以解决方法是：

使用其他内容作为标题，不要将模块作为标题。模块本身不能作为标题。

**Comment by EvanNotFound** [comment]
文本格式出错是因为你把 Folding 整个模块作为了标题，所以 HTML 就把整个模块都当成标题来渲染了

**Comment by rygdsddssd** [comment]
了解，谢谢

从 Windows 版邮件发送

发件人: Evan Luo
发送时间: 2023年3月27日 3:10
收件人: EvanNotFound/hexo-theme-redefine
抄送: rygdsddssd; Author
主题: Re: [EvanNotFound/hexo-theme-redefine] [功能建议] 折叠模块优化版式 (Issue #107)

文本格式出错是因为你把 Folding 整个模块作为了标题，所以 HTML 就把整个模块都当成标题来渲染了

**Comment by EvanNotFound** [comment]
已经修复了 Folding 里面标题被索引问题，请前往更新 v2.0.0 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v2.0.0
