### ISSUE TITLE
[功能建议]可否更新页面布局的自定义？

### ISSUE THREAD

**Issue by Kratpwt** [EvanNotFound/hexo-theme-redefine#116]
**功能概述**
如文章页面非单列排版过于单一，建议提供多种布局类型，或开放用户自定义的布局选项，单列的文章布局实在过于单一，还可添加一些花哨的样式。

**Comment by EvanNotFound** [comment]
好的，我稍后看看

**Comment by EvanNotFound** [comment]
已增加此功能，请前往更新主题 https://github.com/EvanNotFound/hexo-theme-redefine/releases
