### ISSUE TITLE
希望加入 valine 评论功能的接口

### ISSUE THREAD

**Issue by Carolinebaby** [EvanNotFound/hexo-theme-redefine#127]
waline 的评论在国内加载不出来，除非科学上网。希望能加一个 valine 评论的接口。🙏🙏

**Comment by EvanNotFound** [comment]
vercel.app 域名被墙了，请绑定自定义域名，是可以访问的。我的博客/演示站点都是waline

**Comment by EvanNotFound** [comment]
主题以前就有 valine，但是valine有数据漏洞，不安全，所以我就移除valine。而且valine需求量不大，我就先不开发 valine 了，抱歉

如果 waline 配置还是有问题，欢迎加我微信号 `do-not-go-plzzz` 我帮你看看。需要域名也可以联系我，我免费帮你开个子域名
