### ISSUE TITLE
[文件损坏] typora设置主题提供的压缩包解压时提示数据损坏

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#129]
**问题概述**

https://github.com/EvanNotFound/typora-theme-redefine/releases  
1.0.1下Assets提供的两个压缩包解压缩时均出现错误
typora-theme-redefine-1.0.1\redefine\noto-sans-sc-v26-latin-regular.woff2 - 无法读取压缩包数据。

**图片描述**
![image](https://user-images.githubusercontent.com/86097988/230925320-f7e44160-af74-4dd7-97b5-eb0666c3f5be.png)

**Comment by rygdsddssd** [comment]
才发现，我是邮件发送的，github上貌似没有正常显示图片
---
你好，我已成功下载并在Typora中应用，但是我发现您主题中的一些写作模块如折叠，但是如下图，并没有如我想象中的那样正常显示，想请问下是我配置的问题，还是本身就不支持Typora渲染呢
![F37A9A9A-8156-4CE9-A93D-6B7964B8147D](https://user-images.githubusercontent.com/86097988/231349988-d8209330-6215-4fc2-b742-8a7a3b827476.png)
以下是我的Typora状态
![806C8A08-EA2D-4D56-AA83-2F5955942629](https://user-images.githubusercontent.com/86097988/231350063-dd4767ec-16d9-4bb4-9cd4-58504f231423.png)
![4C9FE45A-F71A-4307-AF0E-C374B0E53A69](https://user-images.githubusercontent.com/86097988/231350086-e66f00ea-7f15-4e29-b632-36addf0a3e3e.png)

**Comment by EvanNotFound** [comment]
模块本来就没渲染，我目前还在看有没有解决办法，因为typora能不能加自定义js还不知道

**Comment by rygdsddssd** [comment]
好的，非常期待
