### ISSUE TITLE
[功能建议] 中国大陆境内cdn选取建议

### ISSUE THREAD

**Issue by yzsong06** [EvanNotFound/hexo-theme-redefine#133]
我看这个主题，作者对于中国大陆境内加速的站点cdn是自建的，每月还要付出流量费用。但是我之前在用我那个博客主题的时候，我那个博客主题的作者却是用的饿了么cdn解决的问题（饿了么cdn托管在中国大陆境内华北地区）
例如本主题的某个JS文件加速：
https://npm.elemecdn.com/hexo-theme-redefine@2.1.2/scripts/use-source-data.js

**Comment by EvanNotFound** [comment]
已增加此功能，请前往更新主题 https://github.com/EvanNotFound/hexo-theme-redefine/releases

**Comment by momo54181** [comment]
希望增加cdn1.tianli0.top
