### ISSUE TITLE
[功能建议] 此功能概述

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#137]
**功能概述**
请提供这个功能应该是什么样的

关于目录的宽度没太看明白该如何调整，我尝试调整了sidebar_width 和 content_max_width，得到了不错的效果，但还是希望在文档讲解一下如何调整目录的宽度

ps：这里有处 markdown 出错了 `global.content_max_width`
https://redefine-docs.ohevan.com/basic/global.zh#%E6%96%87%E7%AB%A0%E6%9C%80%E5%A4%A7%E5%AE%BD%E5%BA%A6

下图是我猜测的 sidebar 和 content_max_width 的作用

**图片描述**
可选，可以用你的毕加索画作

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/36620503/234335454-e3f9f406-5fcc-4c53-a142-ea47c85feffa.png">

**Comment by EvanNotFound** [comment]
已修复，感谢 issue
