### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by zfdx123** [EvanNotFound/hexo-theme-redefine#14]
我把网站部署在了github.io上,当然他有一个独立的仓库（user.github.io/blog类似这样,blog是独立的仓库），我在访问的时候发现，主题的资源文件从根目录获得而不是blog/下的资源目录，请问应该怎么解决

**Comment by EvanNotFound** [comment]
请发个github仓库截图，我看一下文件目录格式

**Comment by zfdx123** [comment]
https://github.com/zfdx123/blog
这个是blog仓库

**Comment by zfdx123** [comment]
https://zfdx123.github.io/blog/
这是github.io

**Comment by zfdx123** [comment]
emmmm,现在就是这样的
> url: https://zfdx123.github.io/blog/
> root: /blog/

**Comment by EvanNotFound** [comment]
`url` 链接最后面不要加`/`

比如这样：`url: https://zfdx123.github.io/blog`

试试看

**Comment by EvanNotFound** [comment]
我知道了，是我主题的问题，抱歉抱歉。我会在1小时内修好

**Comment by zfdx123** [comment]
不行，在生成的文件中比如index.html可以看到资源文件前边并没有/blog，我觉得可能是主题生成的问题，使用了决对路径可能

**Comment by zfdx123** [comment]
好的谢谢

**Comment by EvanNotFound** [comment]
修复完毕，请跟随 [官方文档](https://redefine-docs.evanluo.top/docs/quick-start/update) 进行主题更新。

由于你的域名位于子目录，所以首屏图片请使用外链

**Comment by zfdx123** [comment]
好的，谢谢

**Comment by EvanNotFound** [comment]
你导航栏的 `Home` 的链接可以设置成 `/`
这是主题的配置文件，不是站点的。不然 Home 那个键无法点击

**Comment by zfdx123** [comment]
好的，感谢，祝您一切顺利尊敬的开发者

**Comment by zfdx123** [comment]
现在，css加载正常，但是背景即wallhaven-bg-xxx.webp依然从根目录加载，而不是blog导致加载失败，并且我注意到他在请求fonts.gstatic.com下的woff2文件但都报错502无法加载

**Comment by EvanNotFound** [comment]
首屏图片我也不会修😂，所以你能用就用外链url吧，找个图床

**Comment by zfdx123** [comment]
好的 😂😂

**Comment by zfdx123** [comment]
那我在配置文件那个地方把/images/改成/blog/images/吧，这样也可以显示

**Comment by EvanNotFound** [comment]
可以的

**Comment by zfdx123** [comment]
woff2似乎是因为DNS污染造成的，我连接外网OK，感谢您的耐心回复，开源世界您你而精彩，祝你一切顺利

**Comment by EvanNotFound** [comment]
祝好
