### ISSUE TITLE
[功能建议] 首页简介可以换行

### ISSUE THREAD

**Issue by JuTemp** [EvanNotFound/hexo-theme-redefine#154]
**功能概述**
首页的简介可以换行

**图片描述**
现在是这样的
![Screenshot from 2023-05-30 23-19-37](https://github.com/EvanNotFound/hexo-theme-redefine/assets/111566853/026c589a-0312-4a7e-b317-11dbec2987a1)
我想要这样的
![Screenshot from 2023-05-30 23-20-02](https://github.com/EvanNotFound/hexo-theme-redefine/assets/111566853/d4a4d03b-6e5f-4fce-8d23-801287458a85)

在 ```/Hexo/JtpBlog/themes/redefine/layout/_partials/home-content.ejs``` 里
```truncate(strip_html(post.content), {length: 128})```可以把图片去除
但是会去除换行
最好把换行留着 这样才简洁一点

PS:
我尝试了```truncate(post.content, {length: 128})```
但是这样会切断markdown的图片
导致渲染错误

**Comment by EvanNotFound** [comment]
因为大部分文章不适合简介换行，所以如果你需要换行的话，我给文章的 front matter 加了 markdown 渲染引擎。这样的话，可以直接在 front matter 里面的 `excerpt` 项目按照markdown格式写摘要。应该可以满足你的需求了，以下是大概效果。

可以的话，请等待下一版本更新


<img width="1624" alt="Screenshot 2023-06-04 at 1 53 35 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/7e1c071e-bf65-4eb0-9d49-59c20b90503f">
<img width="1624" alt="Screenshot 2023-06-04 at 1 53 40 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/9a285757-012a-476a-926b-a7cb3774441f">
