### ISSUE TITLE
[功能建议] 多级分类

### ISSUE THREAD

**Issue by Freshwlnd** [EvanNotFound/hexo-theme-redefine#157]
**功能概述**
希望能有方便于浏览者观察博客整体组织结构的方式。（最少只需要两级分类的支持，感觉就已经够了）
思路 1：进入分类界面时仅显示一级分类，点击后再进入该分类下的子分类/文章列表。
思路 2：进入分类界面时存在多个面板，每个面板总标题是一级分类，内容是二级分类。
思路 3：不修改分类界面，但增加一个显示博客组织结构的小模块。

**图片描述**
（先这样，再这样，再这样）

**Comment by EvanNotFound** [comment]
<img width="1624" alt="Screenshot 2023-06-22 at 1 48 10 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/9af2d1ef-2795-4853-9ea0-4ab0d03f2f04">

已经写好了，请等待下一版本

**Comment by EvanNotFound** [comment]
已增加此功能，请前往更新主题 https://github.com/EvanNotFound/hexo-theme-redefine/releases
