### ISSUE TITLE
[ENHANCEMENT]Add minimum limit of article recommendation.

### ISSUE THREAD

**Issue by anzai249** [EvanNotFound/hexo-theme-redefine#158]
**Is your feature request related to a problem? Please describe.**
As you can see, the article recommendation works properly when I visit my site on my PC, but if I use my mobile phone, the images will be squashed.

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/32564494/c9d288d0-7baf-47ee-a8bc-e7fd8701af6e)

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/32564494/e40465f9-8431-413b-985e-df6c3b00f734)

**Describe the solution you'd like**
The overall look would be better if the number of recommended articles could be flexibly varied according to the screen size, for example by setting a minimum limit or displaying them vertically when using a mobile phone.

**Describe alternatives you've considered**
None.

**Additional context**
Thank you!

**Comment by EvanNotFound** [comment]
已merge

**Comment by EvanNotFound** [comment]
请等待下一版本更新
