### ISSUE TITLE
[功能建议] 支持更多comment system

### ISSUE THREAD

**Issue by cgjosephlee** [EvanNotFound/hexo-theme-redefine#163]
**功能概述**
gitalk 會讓secret 裸奔，可能有一點點安全疑慮，希望可以支持
- [utterances](https://utteranc.es/)
- [giscus](https://giscus.app/zh-TW)
- [cusdis](https://cusdis.com)

**图片描述**
None.

**Comment by Ching367436** [comment]
我這邊有已經寫好的 giscus support，不過在 dark-light-toggle 的部分有 bug：在網頁讀取好之前切換 dark-light-toggle 有機率造成 giscus 的 dark-light-mode 與網頁的不一致。起因在於 giscus 切換 dark-light-mode 的方式比較特別，還沒有想到要怎麼修，utterances 可能也會遇到類似的問題。所以我目前還沒發 pr。

**Comment by EvanNotFound** [comment]
> 我這邊有已經寫好的 giscus support，不過在 dark-light-toggle 的部分有 bug：在網頁讀取好之前切換 dark-light-toggle 有機率造成 giscus 的 dark-light-mode 與網頁的不一致。起因在於 giscus 切換 dark-light-mode 的方式比較特別，還沒有想到要怎麼修，utterances 可能也會遇到類似的問題。所以我目前還沒發 pr。

没事的，有点 bug 没关系，文档说明一下就行。有时间的话，可以 pr 一下，非常感激

**Comment by EvanNotFound** [comment]
已增加此功能，请前往更新主题 https://github.com/EvanNotFound/hexo-theme-redefine/releases

**Comment by EvanNotFound** [comment]
关于其他评论系统，我后面有时间再增加

**Comment by cgjosephlee** [comment]
謝謝！
