### ISSUE TITLE
[BUG] 更新失败

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#165]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/docs/quick-start/update)**已按更新教程步骤进行**
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/docs/quick-start/update#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)**该网址404**

**Bug 描述**
更新后已进行配置迁移，但显示仍未更新。
- hexo 根目录的网站配置文件 `_config.yml` 
[_config.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/11829490/_config.txt)

- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符
[_config.redefine.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/11829494/_config.redefine.txt)

**复现方法**
未知

**预期结果**
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/2dd36d6f-7bc7-45b0-8206-2f39664493ad)
预计应更新并显示侧边导航栏

**截图**
红框部分已更新
![C V9G8UAR)GT6{ S{OFQK 6](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/11ef6b17-38da-4032-9065-067fce65ce8e)
但是后续执行操作仍提示版本未更新，已执行hexo clean

**电脑（请填写以下信息）：**
 - 操作系统：Windows
 - 浏览器 Edge
 - 版本 [例如 108]

**Comment by EvanNotFound** [comment]
更新方法请见 https://redefine-docs.ohevan.com/getting-started#更新

**Comment by rygdsddssd** [comment]
我已经按照这个进行了迁移
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Evan ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月22日 20:03
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [EvanNotFound/hexo-theme-redefine] [BUG] 更新失败 (Issue #165)
        
      
    
  

更新方法请见 https://redefine-docs.ohevan.com/getting-started#更新

**Comment by EvanNotFound** [comment]
看上去主题没有执行正确的命令进行文件更新，主题文件还是旧版本，和配置文件没关系。

所以请把主题重装。请放心，主题配置文件 `_config.redefine.yml` 不会丢失。请遵循以下步骤进行重装：

1. 如果你是 npm 安装的，请执行命令 `npm uninstall hexo-theme-redefine` 删除主题
2. 如果你是 git 安装的，请删除 `themes` 目录下面的 `redefine` 文件夹删除主题
3. 重新按照[主题文档](https://redefine-docs.ohevan.com/getting-started#%E5%AE%89%E8%A3%85)进行安装，请注意，npm 和 git 版本只能二选其一，不能同时安装

如何判断你安装了 git 版本还是 npm 版本？

- 如果 `themes` 目录下面有 `redefine` 文件夹，那么你安装的就是 Git 版本
- 如果 `node_modules` 目录下面有 `hexo-theme-redefine` 文件夹，那么你安装的就是 npm 版本

npm 和 git 版本只能二选其一，不能同时安装

**Comment by rygdsddssd** [comment]
非常感谢，确实是这个原因，我同时存在git和npm版本，目前问题已解决
        
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Evan ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月23日 01:23
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [EvanNotFound/hexo-theme-redefine] [BUG] 更新失败 (Issue #165)
        
      
    
  

看上去主题没有执行正确的命令进行文件更新，主题文件还是旧版本，和配置文件没关系。
所以请把主题重装。请放心，主题配置文件 _config.redefine.yml 不会丢失。请遵循以下步骤进行重装：

如果你是 npm 安装的，请执行命令 npm uninstall hexo-theme-redefine 删除主题
如果你是 git 安装的，请删除 themes 目录下面的 redefine 文件夹删除主题
重新按照主题文档进行安装，请注意，npm 和 git 版本只能二选其一，不能同时安装

如何判断你安装了 git 版本还是 npm 版本？

如果 themes 目录下面有 redefine 文件夹，那么你安装的就是 Git 版本
如果 node_modules 目录下面有 hexo-theme-redefine 文件夹，那么你安装的就是 npm 版本

npm 和 git 版本只能二选其一，不能同时安装

**Comment by EvanNotFound** [comment]
好的
