### ISSUE TITLE
[功能建议] /page/ 下缺少背景图选项

### ISSUE THREAD

**Issue by lolifamily** [EvanNotFound/hexo-theme-redefine#173]
**功能概述**
希望除了首页以外翻页后也能有首页的背景图
**图片描述**
可选，可以用你的毕加索画作

**Comment by EvanNotFound** [comment]
Redefine v2.2.2 已修复此问题，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并且更新
