### ISSUE TITLE
[BUG] cover对post_assset中相对路径支持

### ISSUE THREAD

**Issue by lolifamily** [EvanNotFound/hexo-theme-redefine#174]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

bug复现和`_config.yml`无关

**复现方法**
复现该 Bug 的步骤：

使用post_assets方式创建新的文章，在对应目录上传图片，然后指定文章的cover为该图片的文件名

**预期结果**
该功能本来应该是怎么样的

会自动展开图片的路径，但是目前会直接按照根目录下进行处理

**截图**
如果可以，请添加截图以帮助解释您的问题。

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
Redefine v2.2.2 已修复此问题，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并且更新
