### ISSUE TITLE
[BUG] 同级分类显示不合适

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#177]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**

假如说一篇文章有如下的同级分类：

``` yml
categories:
  - [影视]
  - [游戏]
```

在文章页面仍然按照“游戏是影视的子分类”的逻辑显示成 `影视 > 游戏`，但实际需要的效果是 `影视 | 游戏`。希望能优化此处的设计。

**预期结果**

分类正确显示为 `影视 | 游戏`。

**电脑**
 - 操作系统：Windows 19
 - 浏览器：Mozilla Firefox
 - 版本：114.0.2

**Comment by EvanNotFound** [comment]
等下我智障了，没事了，你说的是文章是吧？好的我来修

**Comment by EvanNotFound** [comment]
Redefine v2.2.2 已修复此问题，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并且更新
