### ISSUE TITLE
[功能建议] 允许在 front-matter 中为特定文章使用其他版权声明

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#180]
**功能概述**
目前文章的版权声明都是 CC BY-NC-SA 4.0。希望能允许用户在 front-matter 中自定义版权声明。

**Comment by EvanNotFound** [comment]
已更新此功能，请等待下一版本更新。拖了一个月，抱歉了

**Comment by EvanNotFound** [comment]
v2.4.1 已经添加此功能，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新。

感谢等待！
