### ISSUE TITLE
[BUG] Width expand will cause photo arrangement error in masonry page.

### ISSUE THREAD

**Issue by anzai249** [EvanNotFound/hexo-theme-redefine#187]
**Describe the bug**
Here it is. The width expanding or fullscreen function will leave a huge blank on the right of the photos.

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/32564494/092904b9-5972-4b68-8cda-4ec5e3242a11)

**To Reproduce**
1. Go to the 'masonry page', it must have some photos on it.
2. Click on the 'Width expand' button in the settings.
3. See the error.

**Expected behavior**
The photos should be auto-arranged on that page.

**Screenshots**

Normal:

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/32564494/2af37979-21cc-43cd-8371-3589b2bb41b9)

Bug:

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/32564494/91210063-8501-4600-91e8-474f28349330)

**Desktop (please complete the following information):**
 - OS: Windows 11 Professional Workstation 22H2
 - Browser: Chrome 114.0.5735.199 64bit
 - Version: theme-redefine 2.2.2

**Additional context**
None.

**Comment by EvanNotFound** [comment]
https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/ebc35aed-da33-4369-aa91-3ea2d964e46d

修好了

**Comment by EvanNotFound** [comment]
v2.3.0 已经修复，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases
