### ISSUE TITLE
[BUG] 数学公式

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#190]
已经配置了mathjax
![_config_mathjax](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/7650d503-d460-4ed7-82e6-fb203a5a5131)
部分公式不能正常显示
![问题](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/3b251ebe-ffc2-46da-8251-e598b1a56c5e)
![问题2](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/dce8d1fe-32e6-44c1-8553-31ec79cf4510)
数学公式放到提示块里有错误

<img width="1280" alt="问题3" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/59bdc3a2-9505-47e0-af6b-08e14ae10cbd">

![问题4](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/90dbfd96-34df-4a98-86f2-501db714ceb1)

**Comment by EvanNotFound** [comment]
书写行内数学公式请用 `$` 包裹起来。比如 `$ i\hbar\frac{\partial}{\partial t}\psi=-\frac{\hbar^2}{2m}\nabla^2\psi+V\psi $`

<img width="627" alt="Screenshot 2023-07-21 at 10 35 14 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/b2f55968-f4af-4ad5-8609-5010dbd86a07">

跨行请用 `$$` 包裹起来。

<img width="486" alt="Screenshot 2023-07-21 at 10 37 12 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/3af93f11-2e11-4494-97c2-4946fc1d36f3">
<img width="836" alt="Screenshot 2023-07-21 at 10 37 21 PM" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/824c9abf-aab1-4453-be61-310f106874e7">

欢迎参考文档：https://redefine-docs.ohevan.com/plugins/mathjax

提示块显示错误，是bug，我这就去修。

**Comment by EvanNotFound** [comment]
跨行请使用四个 `\`，Instead of two.

比如 

```
$$
\begin{bmatrix}
a & b \\\\
c & d
\end{bmatrix}
$$
```
