### ISSUE TITLE
[BUG] 本地图片缩放后的显示问题。

### ISSUE THREAD

**Issue by Dilettante258** [EvanNotFound/hexo-theme-redefine#198]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
使用了该主题和配套的Tpyora主题，当插入一些图片并设置缩放时，图片语法将变为HTML语法，在Tpyora正常显示，但是浏览器上却无法显示，经过排查应该是HTML语法下的相对路径出了问题。可以修改图片路径，但是修改后Tpyora和浏览器中只能正常显示一个。

**复现方法**
复现该 Bug 的步骤：
Tpyora中插入图片——缩放图片——（图片语法自动转换为HTML语法）
如：`<img src="../images/index_28_0.png" alt="../_images/index_28_0.png" style="zoom:50%;" />`
若修改为：`<img src="/./../images/index_28_0.png" alt="../_images/index_28_0.png" style="zoom:50%;" />`
或`<img src="/images/index_28_0.png" alt="../_images/index_28_0.png" style="zoom:50%;" />`
图片在浏览器中均可正常显示，但是Tpyora下无法根据路径正常找到图片。

**预期结果**
预期应当在Tpyora下缩放图片后，不需要进一步的修改，就能在浏览器和Tpyora同时正常显示。

**截图**
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/15add794-be5f-4d7b-94df-9790c0ef7734)

**电脑（请填写以下信息）：**
 - 操作系统：Windows 11
 - 浏览器 Edge
 - 版本 115.0

**其他**
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/8c672373-5c87-4fc7-9c9a-e2d5d3aea24d)
不正常加载的图片，我确信最简单的办法就是把用绿色方框框柱的那一部分删去了就能解决这个bug。
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/9bd8d942-bb99-485d-8cbe-c3fb2523a138)
正常情况下图片的的位置，不会显示404.

**Comment by EvanNotFound** [comment]
这个问题不是 Bug。使用 hexo 时，图片文件必须存放在 /source 目录下面的文件夹里面，或者 [Post Assets](https://hexo.io/docs/asset-folders.html) 文件夹里面。如果你 Typora 没有配置图床，则直接拖进 Typora 是用不了的。

例如，把所有图片都放在 `/source/images` 文件夹里面，然后在 typora 引用此图片的时候用 `<img src="/images/图片.png />`。静态博客写作就是这样子。如果想直接拖入 Typora，可以配置图床，Typora 会自动上传图片到图床

**Comment by Dilettante258** [comment]
过去几天在忙所以没有及时回复。我想我可能没有表达清楚我的疑问。我的图片已经放在了“/source 目录下面的文件夹里面”。
下面做个对照实验展示一下我的疑问。在Markdown中插入图片有两种写法。
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/1f5cfa00-6715-4021-a2cb-24638bf97ef5)
上图中，在Tpyora编辑器中只有图片1,3,5能正常显示。
现打开浏览器检查
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/48a5ca53-a6db-4c96-8616-e86481decd0e)
上图中，浏览器中却是图片1,2,4,6能正常显示。
_Tpyora编辑器中图片缩放将自动转换为HTML语法。_
这说明，在图片缩放以后，前端部分无法正常根据HTML语法定位图片。
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/415d802c-5acd-40b8-9916-68fa36114e87)
如图所示，如果使用相对路径，那么前端展示图片时路径将存在问题。
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/113875344/2a517ae8-0a62-41ce-87a8-d73daf5a4908)
正常显示的图片如上图所示，中间是没有那段年月日的路径的。
不知道我表达清楚没有，我也不知道这个是不是能不能解决的问题。如果不能，希望作者大大能不能告诉我这个网页链接中间自动添加年月日的路径的功能是否可以关闭？

**Comment by EvanNotFound** [comment]
在 `_config.yml` 中可以配置，具体查看其中的 `permalink` 配置项
