### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by Eliaukilig** [EvanNotFound/hexo-theme-redefine#20]
The theme is very good, but can you support the drop-down menu? thanks 🎈

**Comment by EvanNotFound** [comment]
已经在写这个功能了

**Comment by EvanNotFound** [comment]
Dev分支已更新此功能，目前还在优化主题新增其他功能

着急用的话可以下载 dev 分支源码替换 `themes/redefine` 内文件，

也可以等一天，等我发正式版

**Comment by EvanNotFound** [comment]
已更新，请升级到最新版本 v0.4.0

文档：https://redefine-docs.evanluo.top/docs/configuration-guide/menu
