### ISSUE TITLE
[功能建议] 调整标签，分类，说说，相册页面的左上角标题位置与字体大小统一

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#202]
**功能概述**
调整标签，分类，说说，相册页面的左上角标题位置与字体大小统一
当前这四个页面的标题的位置和大小都不统一

**图片描述**
当前四个页面标题位置与大小如下
zh-CN
![2023-08-06 171356](https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/53b9fd90-e037-4f8f-b3a4-2b9a96366878)
en
![2023-08-06 171720](https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/a5726477-84fe-4544-a5b6-4706eb2820ce)
note: 有点找茬的小建议😂

**Comment by EvanNotFound** [comment]
好的，感谢 Issue

**Comment by EvanNotFound** [comment]
v2.4.1 已经修复，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新
