### ISSUE TITLE
引用路径异常问题汇总

### ISSUE THREAD

**Issue by DwGoing** [EvanNotFound/hexo-theme-redefine#203]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
Tag页和Categories页中链接前缀不一致，导致tag无法正确跳转

**截图**
<img width="438" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/16076018/c34b7479-a9c0-4172-b454-60a5873b9ced">
<img width="618" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/16076018/791ef32b-b2c9-46a7-b393-960fe4b8f344">

**Comment by Super-ZiHao** [comment]
我也遇到了，只要修改了这里就会出现
<img width="1287" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/61496900/b3654ec0-3ee1-4f8b-a857-f5ba96cafeca">

**Comment by DwGoing** [comment]
> 我也遇到了，只要修改了这里就会出现 <img alt="image" width="1287" src="https://user-images.githubusercontent.com/61496900/260037655-b3654ec0-3ee1-4f8b-a857-f5ba96cafeca.png">

虽然删掉blog能解决tags的问题，就担心会影响hexo的其他路径拼接

**Comment by Super-ZiHao** [comment]
我是在表述我也遇到了这个问题，希望有大大能早日修复一下，有点不方便在 GitHubPage 上部署😣😣

**Comment by EvanNotFound** [comment]
非常抱歉，过了比较久才修复，请等待新版本

**Comment by DwGoing** [comment]
<img width="785" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/16076018/ab43c77b-64a3-483e-b9d6-373df8112a5d">
@EvanNotFound 这个问题也顺道处理下呗😂

**Comment by DwGoing** [comment]
<img width="785" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/16076018/ab43c77b-64a3-483e-b9d6-373df8112a5d">
@EvanNotFound 这个问题也顺道处理下呗😂

**Comment by EvanNotFound** [comment]
好的

**Comment by Super-ZiHao** [comment]
还有 logo 处，同 tag 页类似，麻烦看看 👀👀
<img width="466" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/61496900/c1ec7b8e-a8a5-4601-915c-422bbe11e841">

**Comment by EvanNotFound** [comment]
> <img alt="image" width="785" src="https://user-images.githubusercontent.com/16076018/261385981-ab43c77b-64a3-483e-b9d6-373df8112a5d.png"> @EvanNotFound 这个问题也顺道处理下呗😂

这个是因为你的 `_config.redefine.yml` 里面的 `info.url` 中的网址末尾多了个 `/`。

**Comment by EvanNotFound** [comment]
v2.4.1 已经修复，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新

**Comment by DwGoing** [comment]
> > <img alt="image" width="785" src="https://user-images.githubusercontent.com/16076018/261385981-ab43c77b-64a3-483e-b9d6-373df8112a5d.png"> @EvanNotFound 这个问题也顺道处理下呗😂
> 
> 这个是因为你的 `_config.redefine.yml` 里面的 `info.url` 中的网址末尾多了个 `/`。

<img width="461" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/16076018/de7e566d-e1de-4463-ada9-f9c9c67b3c85">

并不是哦😂

**Comment by EvanNotFound** [comment]
怪了
