### ISSUE TITLE
[功能建议] 增加点击图片预览后，可以继续使用滚轮放大或缩小图片的功能

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#206]
**功能概述**
在阅读博客时，有的图片即使点击放大预览也看不清某些文字或者图片放大后尺寸过大
这时希望可以通过滑动鼠标滚轮继续放大或缩小图片

**希望实现此功能的页面**
1. 博客文章详情页
2. 相册页面
3. 说说页面（说说页面插入的图片目前还没有点击放大预览功能）

**Comment by EvanNotFound** [comment]
v2.4.3 已经更新，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新
