### ISSUE TITLE
[BUG] 搜索文章后，点进文章里面不能拖动

### ISSUE THREAD

**Issue by yxmyxmyyy** [EvanNotFound/hexo-theme-redefine#208]
自己搭建后可以搜索，但是进入文章里面不能拖动，我看博主的网站也是这样

**Comment by Krazyu** [comment]
确实诶，PC浏览可以看到 搜索文章后，点进文章右边没有滚动条
另外，如果点击后打开的文章前部分有图片的话，点击图片后，滚动条就出现了，就可以滑动了

**Comment by yxmyxmyyy** [comment]
> 确实诶，PC浏览可以看到 搜索文章后，点进文章右边没有滚动条 另外，如果点击后打开的文章前部分有图片的话，点击图片后，滚动条就出现了，就可以滑动了

你这么一说我又发现一个bug，如果文章有图片，点击放大后如果直接按浏览器的返回，那主页也会卡住，不能滚动

**Comment by EvanNotFound** [comment]
已经在dev版本修复了，请等待更新

**Comment by EvanNotFound** [comment]
v2.4.1 已经修复，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新
