### ISSUE TITLE
[功能建议] 建议添加自定义博文背景图

### ISSUE THREAD

**Issue by newamnesia** [EvanNotFound/hexo-theme-redefine#210]
我没找到，希望添加功能

**Comment by EvanNotFound** [comment]
请详细描述，我没理解

**Comment by newamnesia** [comment]
进入某篇文章后的背景是空白的，请问怎样添加背景图？我是初学者，貌似没有找到相关内容……

**Comment by EvanNotFound** [comment]
目前并不支持。

我也考虑过加背景图，但是有以下两个问题：
- 文章目录 TOC 会因为背景图然后就看不清
- 会让主题不够简洁，阅读体验降低
- 减缓网站加载速度

所以我目前并不打算添加背景

**Comment by newamnesia** [comment]
感谢您的解答
