### ISSUE TITLE
[功能建议] 说说页面的图片增加点击放大预览

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#223]
**功能概述**
说说（本地部署版）页面的图片增加点击放大预览
当前说说插入的图片不支持点击放大，只能在写说说时，通过`width`手动设置图片大小

**Comment by EvanNotFound** [comment]
v2.4.3 已经完成，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新
