### ISSUE TITLE
[BUG] 移动端页面下导航栏下拉菜单字符框位置错误

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#226]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
在移动端页面下导航栏下拉菜单字符框和文字的位置不对应，文本框偏上

**bug截图**
![屏幕录制 2023-08-21 142739](https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/6c790ac6-c4f8-4fab-b61a-b35eea7eee4f)

**Comment by EvanNotFound** [comment]
v2.4.3 已经修复，请查看 https://github.com/EvanNotFound/hexo-theme-redefine/releases 前往更新
