### ISSUE TITLE
[BUG] 移动端导航栏点击无响应

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#230]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**

移动端导航栏在某些情况下会发生点击无响应的情况

**复现方法**

**1. PC（chrome）调整为移动端尺寸，进行测试**

首先刷新页面，点击右上角展开导航栏后，连续点击两次一级菜单，之后会出现右上角展开导航栏图标点击无响应的情况。然后再次刷新页面，点击二级菜单后，则会出现导航栏无法收回的现象，仍然需要刷新页面恢复正常。

**注：如果点击的一级和二级菜单是跳转第三方网站的链接，则无此bug**
视频如下

https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/c8fa4471-231c-45a5-b445-c5a5862993da

**2. 使用 iphone 测试（iPhone13，Safari/chrome）**

点击一级菜单，导航栏会收回，但是收回之后导航栏也会像`测试1` 中的视频一样，点击没反应，需要刷新页面。
点击二级菜单，导航栏同样不会收回，点击× 或者空白也都没反应，需要手动刷新页面。

**3. 使用安卓手机测试（魅族meizu 16s，自带浏览器/via 手机浏览器）**

测试发现，`测试1` 和`测试2`  中的bug并未出现，对测试视频进行慢放发现，测试使用的安卓手机的浏览器会在点击一级/二级菜单后进行一次页面刷新，所以此bug未复现，因为此Bug的临时解决的办法就是手动刷新页面
**注：其他型号手机未能测试，可能是测试手机的特性或者浏览器特性**
视频如下

https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/71f9fbb3-95a8-45b0-9c23-e22bfad4df25

慢放后截图如下，首先进行了一次页内链接跳转，然后浏览器刷新了页面，导致bug未出现

<img width="334" alt="主题自带进度条" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/25a10b06-4132-4c1b-919a-7b12f4f5394a">

<img width="326" alt="浏览器刷新进度条" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/640d9294-e224-450c-b742-cf65f9192216">

**Comment by EvanNotFound** [comment]
已经在 dev 分支修复，请等待下一版本感谢，感谢反馈

**Comment by EvanNotFound** [comment]
呃修复后应该是可以用的啊

**Comment by Krazyu** [comment]
已确认修复
