### ISSUE TITLE
[功能建议] 优化图片预览的操作逻辑

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#233]
**功能概述**

在2.4.4版本下，若是进入了图片预览状态，则只能通过点击图片四周空白区域来退出图片预览状态

若在预览图片时已经将图片放大至占满整个屏幕，那么想要退出预览状态，必须先把图片缩小至四周留出空白，然后点击空白区域才能退出图片预览状态

**建议**

改为：当进入图片预览状态时，无论此时图片是放大还是缩小，无论指针是否在图片区域内，支持单击鼠标直接退出预览状态

当进入图片预览状态时，滚轮负责放大和缩小，更进一步的调整图片预览位置由长按鼠标拖拽实现。鼠标单击也正好是闲置命令

结合 https://github.com/EvanNotFound/hexo-theme-redefine/issues/232 ，进入图片预览状态后，若是在图片内单击，则鼠标指针在单击时变为 grabbing ，然后退出图片预览状态

**2.4.4版本**

https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/474e36cb-79e3-4b90-a8cf-2df9b8c7e026

**Comment by anzai249** [comment]
引入一下fancybox？

**Comment by EvanNotFound** [comment]
太难写了,不会写
