### ISSUE TITLE
[BUG] 更新主题后code_block的字体配置不生效

### ISSUE THREAD

**Issue by ConradSun** [EvanNotFound/hexo-theme-redefine#236]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
更新到2.4.x版本后，代码块的字体配置不再生效，主题中关于代码块的配置如下：
  code_block:
    copy: true # Whether to enable code block copy button
    style: mac # mac | simple
    font: # Custom font
      enable: true # Whether to enable
      family: "Courier" # Font family
      url: "https://fonts.googleapis.com/css2?family=Courier:wght@400;500;600;700&display=swap"

**复现方法**
复现该 Bug 的步骤：
修改code_block中关于font的配置，不起作用，自2.4.x版本后出现，2.3.0版本正常。

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - macOS 14.0 beta6
 - 浏览器 [例如 Chrome, Safari]
 -  Chrome, Safari, Edge浏览器均有相同现象
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
感谢提交，我看看

**Comment by EvanNotFound** [comment]
已经在 dev 版本修复，请等待下一版本，感谢反馈

**Comment by EvanNotFound** [comment]
新版本已经更新/修复此功能，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
