### ISSUE TITLE
首屏下拉提示箭头

### ISSUE THREAD

**Issue by cnbigmx** [EvanNotFound/hexo-theme-redefine#241]
觉得首页背景图全屏情况下有个下滑箭头提示自然一点，可以提示博客内容在下面

**Comment by cnbigmx** [comment]
我在社交链接的配置中添加了arrow-down
然后在mian.js中添加了
` const s = document.querySelector('span.social-contact-item')
    s.innerHTML = `
    <a><i class="fa-solid fa-arrow-down fa-sm"></i></a>
    `
    s.addEventListener('click', function (event) {
      event.preventDefault(); // 阻止默认的链接行为
      // 获取屏幕高度
      var screenHeight = window.innerHeight || document.documentElement.clientHeight;
      // 滚动一个屏幕的距离
      window.scrollBy({
        top: screenHeight,
        behavior: 'smooth' // 平滑滚动效果
      });
    });`
实现的这一功能。

**Comment by EvanNotFound** [comment]
好的我看看，感谢

**Comment by EvanNotFound** [comment]
主题 v2.6.0 已更新/修复此功能，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看
