### ISSUE TITLE
[ENHANCEMENT] support total word count

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#242]
**Is your feature request related to a problem? Please describe.**

当前只有单篇文章的字数统计，希望增加全站所有文章的字数统计。这样就可以显示为：共xx篇文章，共xx字。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsurumi-yizhou** [comment]
It will really make sense.

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本添加，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
