### ISSUE TITLE
[BUG] post里的author信息被config里的覆盖

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#243]
**提交前检查单**
- [ ] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

****

**每篇文章post中的md都可以自定义author，但是目前取值是从config里取的，建议优化一下，谢谢。**

****

**复现方法**
复现该 Bug 的步骤：

**预期结果**
该功能本来应该是怎么样的

**截图**
如果可以，请添加截图以帮助解释您的问题。

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
新版本已经更新/修复此功能，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
