### ISSUE TITLE
[功能建议] 希望將 gitalk 使用的cdn可配置

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#256]
**功能概述**
请提供这个功能应该是什么样的

**图片描述**
可选，可以用你的毕加索画作

```
    <div id="gitalk-container"></div>
    <script <%= theme.global.single_page === true ? 'data-swup-reload-script' : '' %>
            src="//cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.js"></script>
```

這裏寫死了，希望可以配置，比如可以使用 https://cdn.staticfile.org/gitalk/1.8.0/gitalk.min.js

**Comment by Muska-Ami** [comment]
2.5.0好像已经修了cdn的bug?(

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
