### ISSUE TITLE
[BUG] tag移动端显示超宽

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#258]
**提交前检查单**
- [ ] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

**复现方法**
复现该 Bug 的步骤：

**预期结果**
该功能本来应该是怎么样的

移动端也可以正常显示所有tag

**截图**
如果可以，请添加截图以帮助解释您的问题。
![2023-10-03_184638](https://github.com/EvanNotFound/hexo-theme-redefine/assets/17957066/69035640-8f62-4e6e-a9be-bf734909626b)

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
