### ISSUE TITLE
[功能建议] 支持自定义默认文章协议

### ISSUE THREAD

**Issue by Muska-Ami** [EvanNotFound/hexo-theme-redefine#262]
**功能概述**
如题，目前默认是CC-BY-NC-SA 4.0，但不是所有博客都是默认这个协议，一篇一篇添加太麻烦了，希望能自定义，顺带一提CC把翻译过的协议界面地址改了，之前是 `dead.zh` ，现在是 `dead.zh-hans`

**Comment by shawn0915** [comment]
> 现在是 `dead.zh-hans`

这里可以直接指向英文版：https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
