### ISSUE TITLE
[BUG] 链接硬编码问题

### ISSUE THREAD

**Issue by lolifamily** [EvanNotFound/hexo-theme-redefine#263]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
这里三个链接都被硬编码，不能调整末尾是否有``/``
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/47876607/54cc53b9-5f15-4247-8563-ce86e33c4cbb)
这里的链接硬编码为/，没有考虑到子目录托管网站的情况
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/47876607/cce0043e-11be-468c-b13d-32d4b01e0862)

**Comment by EvanNotFound** [comment]
这些链接并不是写死。
![CleanShot 2023-11-12 at 21 04 10@2x](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/7a34f947-4195-4e08-ad15-01ed077fb4a5)
