### ISSUE TITLE
[BUG] 想换背景图片不成功，本地可以但github.io不可以。每次g -d 或者 s 总是显示这个错误

### ISSUE THREAD

**Issue by jelasin** [EvanNotFound/hexo-theme-redefine#265]
![图片](https://github.com/EvanNotFound/hexo-theme-redefine/assets/97788570/81a71a77-f535-44d0-a285-34587b41af8e)

**Comment by EvanNotFound** [comment]
请提供配置文件

**Comment by jelasin** [comment]
home_banner:
  # Whether to enable home banner
  enable: true
  # style of home banner
  style: fixed # static or fixed
  # Home banner image
  image: 
    light: /images/light.jpg # light mode
    dark: /images/dark.jpg # dark mode

navbar:
  # Auto hide navbar
  auto_hide: false
  # Navbar background color
  color:
    left: "#000000" #left side 
    right: "#ffffff"  #right side
    transparency: 50 #percent (10-99)

**Comment by Muska-Ami** [comment]
> home_banner:
> 
> # Whether to enable home banner
> enable: true
> 
> # style of home banner
> style: fixed # static or fixed
> 
> # Home banner image
> image: light: /images/light.jpg # light mode dark: /images/dark.jpg # dark mode
> 
> navbar:
> 
> # Auto hide navbar
> auto_hide: false
> 
> # Navbar background color
> color: left: "#000000" #left side right: "#ffffff" #right side transparency: 50 #percent (10-99)

建议用代码块包裹 `\`\`\``

**Comment by catnap826** [comment]
我也遇到这个问题了，本地可以换背景图片，但是部署到GitHub就不行
看了下库里的index文件，image url已经改了，但是网页还是不生效
"home_banner":{"enable":true,"style":"static","image":{"light":"https://photo.catnap.eu.org/photo/2023/11/202311262153430.png","dark":"https://photo.catnap.eu.org/photo/2023/11/202311262153430.png"}

**Comment by catnap826** [comment]
关于换背景，刚才整个重装了hexo和这个主题，再重新部署就没问题了，也许这是偶发性bug吧
重装前记得把配置文件保留下来
