### ISSUE TITLE
[功能建议] waline 表情自定义选项

### ISSUE THREAD

**Issue by lolifamily** [EvanNotFound/hexo-theme-redefine#266]
see https://waline.js.org/guide/features/emoji.html

**Comment by lolifamily** [comment]
@EvanNotFound 还可以考虑添加RECAPTCHA_V3_KEY和TURNSTILE_KEY的选项，这个需要在客户端上配置

**Comment by EvanNotFound** [comment]
主题 v2.6.0 已更新/修复此功能，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看
