### ISSUE TITLE
[功能建议] 标题栏增加语言切换按钮

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#269]
**功能概述**
请提供这个功能应该是什么样的

**图片描述**
可选，可以用你的毕加索画作

---
增加语言切换按钮，可以选择切换En/Jp/Fr

**Comment by EvanNotFound** [comment]
由于 Hexo 是静态博客，我目前还没有找到切换语言的实现路径。如有方法，欢迎提出
