### ISSUE TITLE
[BUG] 相册占位符动画与实际列数不一致

### ISSUE THREAD

**Issue by Krazyu** [EvanNotFound/hexo-theme-redefine#270]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
相册图片加载完成前的动画列数和加载后不一致

**复现方法**
网页调整为两列图片宽度时刷新网页

**视频**

https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/44818ee0-f9fd-4d5d-a43b-0aa6f9e2d83f

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
