### ISSUE TITLE
[功能建议] 增加改变标题之间行间距的功能

### ISSUE THREAD

**Issue by Huasushis** [EvanNotFound/hexo-theme-redefine#272]
**功能概述**
有时候正文内容比较少，标题之间距离比较大看起来很不美观，不是很紧凑。

**图片描述**
可选，可以用你的毕加索画作

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本添加，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
