### ISSUE TITLE
Updating from v2.2.1 to 2.5.x

### ISSUE THREAD

**Issue by Kurasami** [EvanNotFound/hexo-theme-redefine#275]
Can I simply git clone and overwrite the files I already have? Is it going to break anything?

I can't do the traditional "npm" way.

**Comment by Muska-Ami** [comment]
If you doesn't modified any thing except `_config.yml` , you can backup your `_config.yml` execute this command to update:
```
git pull
```

**Comment by EvanNotFound** [comment]
Using the configuration file in the root of hexo site `_config.redefine.yml` will solve the problem. after pasting your config items in it, you can safely `git pull`
