### ISSUE TITLE
[BUG] mathjax默认解析开关无效

### ISSUE THREAD

**Issue by WYCTSTF** [EvanNotFound/hexo-theme-redefine#276]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [x] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
配置文件中mathjax部分为每一篇markdown默认启用的`every_page`设置为true之后并没有生效，文章中不添加`mathjax: true`仍然不解析数学公式

**预期结果**
`every_page`设为true之后不用在文章里单独添加`mathjax: true`就可以解析数学公式

**电脑（请填写以下信息）：**
 - 操作系统：MacOS14.0
 - 浏览器 Chrome
 - 版本 117.0.5938.149 正式版本 arm64

**Comment by EvanNotFound** [comment]
我这边测试是没问题的。

请查看你的配置。

![CleanShot 2023-11-12 at 20 57 00@2x](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/c5c26f8a-ac30-459b-bee5-b212793eb7bb)
![CleanShot 2023-11-12 at 20 56 46@2x](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/e9ed4dfb-68ef-457a-8c14-c5b58c08e0bb)
![CleanShot 2023-11-12 at 20 56 35@2x](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/ee0d032d-2fbf-4e88-9be6-dba45bb75039)
