### ISSUE TITLE
[功能建议] Gitalk添加proxy选项

### ISSUE THREAD

**Issue by Muska-Ami** [EvanNotFound/hexo-theme-redefine#277]
**功能概述**
如题，由于Gitalk默认CORS-Anywhere地址经常被墙，建议添加该参数允许修改 `proxy` 项，参考
- https://github.com/Muska-Ami/hexo-theme-redefine/blob/28812137eb83a1eee2550740e40231fd3add579e/layout/_partials/comments/gitalk.ejs#L30
- https://github.com/Muska-Ami/hexo-theme-redefine/blob/be3eb414568bd30b54d57f6c28a4d1b8c259fa62/_config.yml#L314

**Comment by Muska-Ami** [comment]
这个问题不能再拖力（其实只要改两行罢）

**Comment by EvanNotFound** [comment]
主题 v2.6.0 已更新/修复此功能，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看
