### ISSUE TITLE
[BUG] 疑似 waline 评论不显示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#278]
**Bug 描述**
疑似 waline 评论不显示。
waline 界面为 waline.ncwzdlsd.top。已正确填写
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/117651674/3fa5ece0-3397-41b3-be9b-45ff6db4be39)
怀疑为 CDN 问题
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/117651674/61ec7da3-1978-4f9e-8256-8f911b13676d)

**Comment by ncwzdlsd** [comment]
确认为 CDN 问题，将 CDN 改为 false 后问题解决，希望能尽快解决，十分感谢

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
