### ISSUE TITLE
[BUG] 使用一言提供副标题刷新页面副标题不更新

### ISSUE THREAD

**Issue by null-qwerty** [EvanNotFound/hexo-theme-redefine#280]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
我在博客上部署了该主题，使用一言提供副标题，但发现副标题循环显示一句话，我在文档中并未找到相关处理方法。在翻阅[一言的语句接口文档](https://developer.hitokoto.cn/sentence/)时考虑过可能是QPS限制，测试接口后认为不是QPS限制导致的问题。请问我在哪能够找到这个问题的解决方法，或者我是否少配置了什么参数？
相关配置：
![1](https://github.com/EvanNotFound/hexo-theme-redefine/assets/114760660/e5b2199a-ca9e-44f3-957f-38b578dee076)

**复现方法**
复现该 Bug 的步骤：
部署一言作为副标题

**预期结果**
每次副标题内容不同

**电脑（请填写以下信息）：**
 - 操作系统：windows10
 - 浏览器 firefox-dev
 - 版本 120.0b3

**Comment by Krazyu** [comment]
看了下你的博客，每次刷新页面后更新一言文字，应该是没有问题。

**Comment by null-qwerty** [comment]
> 看了下你的博客，每次刷新页面后更新一言文字，应该是没有问题。

感谢您的回复，应该是我这边网络或者浏览器设置的问题。
