### ISSUE TITLE
[BUG] 文章无法打开

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#282]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在
- [x] 已经更新到主题最新版本
- [x] 刚更新完主题出现此问题，已经确认同步主题配置文件

**Bug 描述**
hexo s 后,访问，控制台报错
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/3190e9bd-c1d1-461f-8ed8-ecb65bbbea81)
直接访问网站(homehu.top无法打开文章)
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
[根目录_config.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/13224691/_config.txt)
[根目录_config.redefine.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/13224710/_config.redefine.txt)
[node_modul内_config.txt](https://github.com/EvanNotFound/hexo-theme-redefine/files/13224711/node_modul._config.txt)

- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

**预期结果**
该功能本来应该是怎么样的

**截图**
如果可以，请添加截图以帮助解释您的问题。

**电脑（请填写以下信息）：**
 - 操作系统：Windows
 - 浏览器 Edge
     - 版本 118.0.2088.76 (正式版本) (64 位)

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
你的 config.redefine.yml 中

```
# Site URL
  url: rygdsddssd.github.io
```
这一部分，需要加上 `https://`

**Comment by rygdsddssd** [comment]
谢谢，已解决
