### ISSUE TITLE
[BUG] folding 折叠 yellow orange 颜色一样

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#289]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

2.5.0 版本
{% folding yellow::Folding 测试： 点击查看更多 %}
{% folding orange::Folding 测试： 点击查看更多 %}
这俩颜色一样

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
