### ISSUE TITLE
关于代码块样式

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#29]
能不能提供一个更加简约的代码块样式啊QAQ，甚至像GitHub自带Markdown里的代码块风格这么简约的都可以，Mac风的代码块看着有点杂

**Comment by EvanNotFound** [comment]
已在 `v0.4.4` 增加，详见 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v0.4.4)
