### ISSUE TITLE
[BUG] 有序列表内写无序列表，无序列表会转成有序列表

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#290]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

2.5.0
```
6. Terminated  
   - 线程自己运行结束
   - 线程因为触发异常而被结束
```
会显示成
```
6. Terminated  
   1. 线程自己运行结束
   2. 线程因为触发异常而被结束
```

怀疑是渲染器的问题，改成 `hexo-renderer-markdown-it` 依旧没有效果

将主题改成默认 landscape 后，渲染错误消失

### 复现方法

```
6. Terminated  
   - 线程自己运行结束
   - 线程因为触发异常而被结束
```

### 预期结果

6. Terminated  
   - 线程自己运行结束
   - 线程因为触发异常而被结束

**Comment by EvanNotFound** [comment]
Redefine 主题 `v2.5.1` 已修复/更新此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新主题
