### ISSUE TITLE
[BUG] 如何加入自己的页面

### ISSUE THREAD

**Issue by rygdsddssd** [EvanNotFound/hexo-theme-redefine#294]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

![110](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/db5972fb-a30c-468d-9848-d10defb9d065)
![112](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/41413ded-1077-4c9a-9efe-b6e56ef2c154)
如图，我添加了/me文件夹，在其中放了我的页面代码
在其中/static中放了css以及js
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/d6a1386a-0497-4528-90de-b6ba4aaf9431)
但是最后似乎页面是按照redefine的样式展现的，而并没有按css文件中那样。
应该怎么样做才能在点击me后看到自己的页面样式

### 预期结果

![111](https://github.com/EvanNotFound/hexo-theme-redefine/assets/86097988/3bdf6ef6-c06c-4ff7-aa50-1dfa63bc4187)

### 电脑操作系统

Windows

### 浏览器

Edge

### 版本

119.0.2151.44 (正式版本) (64 位)

**Comment by EvanNotFound** [comment]
请在每次使用 `hexo g`生成站点静态文件后，在 public 文件夹中创建 `me` 文件夹，然后复制你的 `index.html` 文件到里面。

Hexo 不支持从 source 目录自动包含 html。

**Comment by rygdsddssd** [comment]
> 请在每次使用 `hexo g`生成站点静态文件后，在 public 文件夹中创建 `me` 文件夹，然后复制你的 `index.html` 文件到里面。

文件夹中已经存在了me文件夹，这是恰好重名吗。查看发现其中的index.html文件已经嵌入了我自己的index的代码

**Comment by EvanNotFound** [comment]
把 source 文件夹的 me 文件夹删掉

**Comment by rygdsddssd** [comment]
> 把 source 文件夹的 me 文件夹删掉，重新 `hexo g`

试了，但还是像第一张图那样被渲染成了redifine的样式？或许应该设置渲染时跳过这个文件夹？似乎需要设置skip_render属性

**Comment by rygdsddssd** [comment]
将_config.yml中
> # Directory
>>*****
>>skip_render:
修改成
skip_render: me/**
问题就解决了

**Comment by EvanNotFound** [comment]
是吗？好的那就可以了
