### ISSUE TITLE
[BUG] 代码块无法正确显示solidity语言

### ISSUE THREAD

**Issue by f4tb3e** [EvanNotFound/hexo-theme-redefine#295]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

语言为solidity的代码块在生成之后，语言标签会变成Plaintext，且无法语法高亮。
md文件：
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/101127314/a6d8a9bd-cf67-400b-96ae-99e08b322d4a)
生成后：
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/101127314/3f5ef97c-73cc-4b8b-9358-7b53149478f7)

### 复现方法

写一个solidity的代码块，然后hexo g

### 预期结果

能正确识别并高亮solidity。我在想是不是该主题使用的代码高亮引擎不支持solidity语言，本来想提pr的，奈何找不到 :P

### 电脑操作系统

Windows

### 浏览器

Chrome

### 版本

119

**Comment by EvanNotFound** [comment]
你好，

主题使用的是 `highlight.js` 作为语法高亮引擎。目前 highlight.js 原生不支持 solidity 语言，需要额外安装 `highlightjs-solidity` 库：https://github.com/highlightjs/highlightjs-solidity

如有需要，可以自行研究一下，修改一下主题文件应该就可以。
