### ISSUE TITLE
[BUG] 文章页面相关ejs编译失败

### ISSUE THREAD

**Issue by sx349** [EvanNotFound/hexo-theme-redefine#298]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

尝试用hexo server本地预览时，提示有两个ejs文件编译失败，分别是：
- layout/article-content.ejs
- layout/_meta/article-copyright.ejs

提示是：
`ERROR Process failed: xxx.ejs`
`SyntaxError: Unexpected token '.' in xxx.ejs while compiling ejs`

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/4407224/de6bae33-6c9d-4811-8f67-f921d64631f1)

结果能够正常显示首页，但是点进任意文章页后显示的是ejs源代码：

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/4407224/bdb328ad-f236-49aa-b12c-84a6ed2e1975)

### 复现方法

- 新建文件夹
- 打开Git Bash
- 使用`hexo init`初始化
- 使用`npm install hexo-theme-redefine@latest`安装主题
- 在`_config.yml`中将主题更改为`redefine`
- 新建`_config.redefine.yml`并按照文档插入所有内容
- 使用`hexo s`本地预览

### 预期结果

文章页面正常显示

### 截图

参见Bug描述

### 电脑操作系统

Windows 10 Pro 22H2

### 浏览器

Chrome 119.0.6045.124 (Official Build) (64-bit) (cohort: Stable) 

### 版本

v2.5.0

**Comment by EvanNotFound** [comment]
请把文章markdown源文件发一下

**Comment by sx349** [comment]
[hello-world.md](https://github.com/EvanNotFound/hexo-theme-redefine/files/13350097/hello-world.md)

复现的时候是重新初始化的，所以就是默认的这个Hello World文章。

一开始出现问题是迁移的本来的站点，所以内容什么都有，都显示为ejs源代码格式。

**Comment by sx349** [comment]
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/4407224/56629215-473a-4eab-9174-03cea1cbd0c2)

顺便这是`hexo version`的结果

**Comment by EvanNotFound** [comment]
请尝试更新到主题最新版 v2.5.1

再看看问题是否存在

**Comment by sx349** [comment]
刚刚更新到了v2.5.2，问题仍然存在，而且还多了一个：

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/4407224/306e3574-6586-4e93-a2d0-618b03bd8e30)

`
ERROR Script load failed: node_modules\hexo-theme-redefine\scripts\events\welcome.js
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\wssx3\Documents\testblog\node_modules\axios\index.js
require() of ES modules is not supported.
require() of C:\Users\wssx3\Documents\testblog\node_modules\axios\index.js from C:\Users\wssx3\Documents\testblog\node_modules\hexo-theme-redefine\scripts\events\welcome.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\wssx3\Documents\testblog\node_modules\axios\package.json.
`

**Comment by EvanNotFound** [comment]
你好，请尝试更新你的 hexo-cli 版本。目前版本是 4.1.0，你的 hexo-cli 版本已经过时

**Comment by sx349** [comment]
解决了，不是hexo-cli的问题，是我太久没更新node.js了……更新到最新版本之后显示就正常了。

非常感谢！

**Comment by EvanNotFound** [comment]
好的
