### ISSUE TITLE
关于首页的文章摘要

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#30]
建议增加一个开启或关闭自动截取文章摘要的功能，可以优化主页的展示

**Comment by EvanNotFound** [comment]
本来就可以自定义首页文章摘要，详见文档：https://redefine-docs.evanluo.top/docs/advanced/exercpt

**Comment by ncwzdlsd** [comment]
> 本来就可以自定义首页文章摘要，详见文档：https://redefine-docs.evanluo.top/docs/advanced/exercpt

我指的是能不能不显示任何摘要，即摘要为空QAQ

**Comment by EvanNotFound** [comment]
好吧，下一版本加上

**Comment by EvanNotFound** [comment]
已在 `v0.4.4` 增加，详见 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v0.4.4)
