### ISSUE TITLE
[BUG] note notel 没有结束符会 不显示文字

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#301]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

如果在文章里写一个 {% note info %} 但是不写 {% endnote %} ，从 {% note info %} 之后的文章就都不加载了

**Comment by DarkFlameMasterDev** [comment]
它会导致整篇文章后续的都没了，后面所有的都没了

**Comment by EvanNotFound** [comment]
这个语法是 Hexo 官方的 Helper，我没法改。抱歉。
