### ISSUE TITLE
[BUG] 有序列表偏左没有修复成功啊

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#302]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

https://github.com/EvanNotFound/hexo-theme-redefine/issues/288
我添加了一个新的回复

**Comment by EvanNotFound** [comment]
你的有序列表偏左是因为英文字体使用了 `monospace` 等距字体，一个 `.` 就会占一个标准字符，导致偏左。

如图我在更改你英文字体后，显示正常
![CleanShot 2023-12-08 at 15 03 08@2x](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/82d30b07-bd3e-4ce6-a304-f8fa65940a03)
