### ISSUE TITLE
[功能建议]：微信图片过小

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#303]
### 功能描述

<img width="1517" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/36620503/6dc02a5d-2795-4e6f-a155-dbd40536d479">
<img width="265" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/36620503/3e28821b-34e8-49ca-912c-b682a94a3325">

**Comment by EvanNotFound** [comment]
在 67a7cd2 修复

**Comment by EvanNotFound** [comment]
主题 v2.6.0 已更新/修复此功能，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看
