### ISSUE TITLE
[BUG] npm安装后

### ISSUE THREAD

**Issue by xiaoeeyu** [EvanNotFound/hexo-theme-redefine#307]
### Pre-Submission Checklist

- [ ] I've run `hexo clean`, but the problem persists.
- [ ] [I've updated to the latest theme version](https://redefine-docs.ohevan.com/getting-started#update)
- [ ] [Post theme update, I've ensured the theme's configuration is in sync](https://redefine-docs.ohevan.com/getting-started#migrate-configuration)

### Describe the Bug

ERROR Check latest version failed: Error: read ECONNRESET
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v18.14.0

### Reproduction Steps

执行
npm install hexo-theme-redefine@latest

git clone https://github.com/EvanNotFound/hexo-theme-redefine.git themes/redefine

hexo clean

**Comment by EvanNotFound** [comment]
是 Bug，在修复了

**Comment by EvanNotFound** [comment]
请问是否能提供更多详细信息

**Comment by xiaoeeyu** [comment]
<img width="864" alt="2023-11-21_142023" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/ef646e70-ee68-43f4-baab-d441f299f177">
<img width="891" alt="2023-11-21_142310" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/e5d0f486-2de9-4cdf-94e0-1932c7a7bca4">

**Comment by xiaoeeyu** [comment]
> 请问是否能提供更多详细信息

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/3659b976-8246-4d69-b7be-b4127a771616)
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/436fb7d0-1b23-447e-bbb9-4e097dd15763)
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/aca12873-bb5d-4ac6-8f61-6ba9e12ae3dd)
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/84135528/2ea3eed4-49eb-4fbe-8c1b-5e444da666da)

**Comment by EvanNotFound** [comment]
npm 安装主题请使用 `npm install hexo-theme-redefine@latest`。请不要忘记后面的 `@latest`。

同时 git 版本和 npm 版本不能同时安装，如果安装了一个请卸载另一个。

卸载 npm 版本指令：`npm un hexo-theme-redefine`
卸载 git 版本：删除 `themes` 目录下面的 `redefine` 文件夹

从你图里能看出你同时安装了两个版本，请卸载其中一个

**Comment by EvanNotFound** [comment]
主题 Bug 已修复。感谢反馈
