### ISSUE TITLE
[BUG] 非首页无法显示背景图片

### ISSUE THREAD

**Issue by Huasushis** [EvanNotFound/hexo-theme-redefine#317]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

更新主题后发现非第一页的背景图片没有了。黑夜白天模式都没有，尝试在 linux 内进行复现。

### 复现方法

由于我没有在家，在 linux 内尝试复现，安装最新版本的 npm，然后安装 hexo 并下载最新版本的主题，保证 _posts 文件夹中至少11个文件后，运行 `hexo clean` `hexo g` `hexo s` 后进入网页发现第二页以后背景图片都没有显示。

### 预期结果

显示背景图片。

### 电脑操作系统

Ubuntu 23.10

### 浏览器

Firefox

### 版本

2.6.0

**Comment by EvanNotFound** [comment]
请把网页发来看看

**Comment by viEcho** [comment]
此问题我已发现，home-banner-backgroud.ejs中代码按如下格式替换即可，当然这里写死了；你也可以按首页变量获取方式，但是自认为这种写法比较高效；且此ejs中代码较少，背景图更换不频繁怎么写无所谓解决问题即可

<div class="home-banner-background transition-fade fixed top-0 left-0 w-screen h-screen scale-125 sm:scale-110 box-border will-change-transform bg-cover">
    <img src="/images/wallhaven-wqery6-light.webp" alt="home-banner-background" class="w-full h-full object-cover dark:hidden">
    <img src="/images/wallhaven-wqery6-dark.webp" alt="home-banner-background" class="w-full h-full object-cover hidden dark:block">
</div>

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本修复，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
