### ISSUE TITLE
[BUG] v2.6.0 下 head_end 位置的 injector，实际注入的位置在 body

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#321]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

不太确定是不是 Redefine 的 bug，但我测试新建一博客使用默认的 landscape 主题或 Redefine v2.5.6 无此问题，切换到 Redefine v2.6.0，就出问题。

我使用 Hexo 的注入器（injector）实现一些自定义的功能。根据[文档](https://hexo.io/api/injector)，`head_end` 位置的注入器应该将代码注入到 `</head>` 前，但在 Redefine v2.6.0 下，代码被注入到 body。

### 复现方法

编写一个 `head_end` 位置的 injector，在 Redefine v2.6.0 下观察注入效果。

### 预期结果

注入的内容在 `</head>` 前。

### 电脑操作系统

Windows

### 浏览器

 Mozilla Firefox、Microsoft Edge

### 版本

120.0.1、120.0.22

**Comment by bianyukun1213** [comment]
应该跟 preloader 有关系。我在网络请求里看到的是正常的 HTML，检视元素时就变了；然后关闭 preloader，检视元素时也正常了。

**Comment by bianyukun1213** [comment]
似乎是环境问题。

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本修复，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
