### ISSUE TITLE
[BUG] 关闭 preloader 后，页脚下出现空白

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#322]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

关闭 preloader 后，页脚下出现空白。

### 复现方法

将 `preloader` 设为 `false`。

### 预期结果

页脚正常显示，即下方无空白。

### 截图

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/24708556/3d9b01fa-9a13-475a-bccb-cfa3ac6fcd3e)

### 电脑操作系统

Fedora

### 浏览器

Mozilla Firefox

### 版本

120.0.1

**Comment by bianyukun1213** [comment]
是[这行](https://github.com/EvanNotFound/hexo-theme-redefine/blob/4e8e58e0b8fee8ec33b65d5bb14aab5c039a5aa4/layout/_partials/scripts.ejs#L45C44-L45C44)末尾多出来的单引号造成的。

**Comment by EvanNotFound** [comment]
感谢，dev 已修复 72f3a8a

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本修复，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
