### ISSUE TITLE
[BUG] 页面中图片的标注无法居中

### ISSUE THREAD

**Issue by bianyukun1213** [EvanNotFound/hexo-theme-redefine#323]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

文章中图片下方的标注居中显示，但是页面中图片下方的标注未应用此样式。

### 复现方法

新建一页面，插入图片。

### 预期结果

标注居中。

### 截图

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/24708556/bc348699-1c5e-4caf-a6de-05b937c2c040)

### 电脑操作系统

Fedora

### 浏览器

Mozilla Firefox

### 版本

120.0.1

### 其他

文章中的图片标注被 `.post-page-container figure.image-caption figcaption` 选择器选中从而应用居中样式；但页面中不存在 `.post-page-container`，而是 `.page-template-container`，因此未如期应用居中样式。

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本修复，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
