### ISSUE TITLE
[功能建议]：categories中列间距调整，及a标签无须整行选中效果避免误触跳转

### ISSUE THREAD

**Issue by viEcho** [EvanNotFound/hexo-theme-redefine#324]
### 功能描述

1.categories文章列标题太紧凑，调整font-size由1.5rem调整为1.05rem正好合适；
2.categories文章列标题a标签宽度是整行宽度，下拉滑动时不小心点击会自动跳转，建议改为宽度根据文本自适应；增加width:fit-content;
3.导航栏宽度不够，限制了max-width应适当调整，增加变量百分比控制调整；目前我自己改完是为了省事直接写死了

### 图片描述

优化1：
![1](https://github.com/EvanNotFound/hexo-theme-redefine/assets/45657757/02f969ca-b01f-4d34-b0bd-2f0972b7757e)

优化2:
![2](https://github.com/EvanNotFound/hexo-theme-redefine/assets/45657757/c21ac6c1-e363-4ee0-9b7a-adb6c8fb342d)

优化3:
![3](https://github.com/EvanNotFound/hexo-theme-redefine/assets/45657757/cda2d71f-6e3a-4ba3-8638-9ca5b414a166)
  
优化3相应修改位置：
```styl
.navbar-content
    position relative
    height 100%
    width 88%
    //width $main-content-width--注掉
    //max-width $content-max-width--注掉
    display flex
    flex-direction row
    justify-content space-between
    align-items center
    z-index $z-index-5
    transition max-width 0.3s ease

    &.has-home-banner
      //max-width $content-max-width * 1.2--主掉
```

**Comment by EvanNotFound** [comment]
已在 Redefine `v2.6.1` 版本修复，请前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases 查看并更新主题
