### ISSUE TITLE
[BUG] 豆瓣书单显示异常

### ISSUE THREAD

**Issue by stephen0316** [EvanNotFound/hexo-theme-redefine#325]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

首次进入书单/影单 页面无数据显示，每次需要手动刷新后才能正常显示

### 复现方法

点击“书单”进入页面，发现无数据展示
<img width="1711" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/55699331/dcdaa9ad-8c82-4a9e-b174-1a438f153412">
<img width="1480" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/55699331/bdd9e6d0-209d-4ed8-9adf-33e18631d2bf">

### 预期结果

进入页面就能正常加载显示

### 截图

<img width="1480" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/55699331/bdd9e6d0-209d-4ed8-9adf-33e18631d2bf">
<img width="1472" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/55699331/bacf2cf5-b7ef-4e49-b395-6ac56522a89c">

### 电脑操作系统

macos

### 浏览器

Chrome

### 版本

120.0.6099.109

**Comment by anzai249** [comment]
插件和swup不兼容
在script标签加个`data-swup-reload-script`应该就行了

**Comment by stephen0316** [comment]
在哪个script标签加呀（不要意思，非科班出身，平时搞着玩，对前端这一套不是很了解）


| |
杨航
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月2日 17:08 |
| 收件人 | ***@***.***> |
| 抄送人 | stephen ***@***.***> ,
***@***.***> |
| 主题 | Re: [EvanNotFound/hexo-theme-redefine] [BUG] 豆瓣书单显示异常 (Issue #325) |

插件和swup不兼容
在script标签加个data-swup-reload-script应该就行了

**Comment by bianyukun1213** [comment]
书单用的是某个 Hexo 插件插入的吗？能发一下链接吗？估计可以用 Filter 解决。

**Comment by stephen0316** [comment]
对，插件链接如下：https://github.com/mythsman/hexo-douban



| |
杨航
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月3日 15:16 |
| 收件人 | ***@***.***> |
| 抄送人 | stephen ***@***.***> ,
***@***.***> |
| 主题 | Re: [EvanNotFound/hexo-theme-redefine] [BUG] 豆瓣书单显示异常 (Issue #325) |

书单用的是某个 Hexo 插件插入的吗？能发一下链接吗？估计可以用 Filter 解决。

**Comment by bianyukun1213** [comment]
是分页脚本没有加载导致的。我写了个脚本可以修复这个问题。

1. 在 `_config.yml` 里把 `douban` 的 `builtin` 设为 `true`，让修复脚本可以在豆瓣插件生成页面之后修改它们；
2. 运行 `npm install cheerio` 安装 cheerio；
3. 在站点根目录下的 `scripts` 目录（没有就新建）下新建 `filter-douban-fix.js`（别的名称也可以）；
4. `filter-douban-fix.js` 里写如下代码，保存，重新生成站点。

``` javascript
const cheerio = require('cheerio');
const config = hexo.config;

let doubanPagePaths = [];
const doubanBookConfig = config.douban.book;
const doubanMovieConfig = config.douban.movie;
const doubanGameConfig = config.douban.game;
const doubanSongConfig = config.douban.song;
if (doubanBookConfig && doubanBookConfig.path)
    doubanPagePaths.push(doubanBookConfig.path);
if (doubanMovieConfig && doubanMovieConfig.path)
    doubanPagePaths.push(doubanMovieConfig.path);
if (doubanGameConfig && doubanGameConfig.path)
    doubanPagePaths.push(doubanGameConfig.path);
if (doubanSongConfig && doubanSongConfig.path)
    doubanPagePaths.push(doubanSongConfig.path);

hexo.extend.filter.register('after_render:html', (htmlSrc, local) => {
    if (doubanPagePaths.includes(local.page.path)) {
        let $ = cheerio.load(htmlSrc);
        $('.hexo-douban-pagination+script').attr('data-swup-reload-script', '');
        return $.html();
    }
    return htmlSrc;
}, 20);
```

cheerio 是用来选择 HTML 文件里分页脚本的 script 标签的，如果自己匹配、替换的话，就不用安装，运行应该也会快一点点。

**Comment by bianyukun1213** [comment]
或者在 Redefine 配置里直接关闭单页模式 `single_page` 也可以，就不用再写脚本修了。

**Comment by stephen0316** [comment]
解决了哥们儿，我直呼泪目，谢谢！

**Comment by bianyukun1213** [comment]
> 解决了哥们儿，我直呼泪目，谢谢！

那可以关掉 issue 了。
