### ISSUE TITLE
[BUG] 暗色主题，搜索框文字颜色和背景色一样，无法辨认

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [EvanNotFound/hexo-theme-redefine#327]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

## 注意看这里，我写的是 1234，并选中了 34，底色和文字颜色一致导致 文字 无法看到
<img width="1318" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/36620503/df509ee6-58f5-4cab-acab-ae2aaf959ea2">

### 复现方法

暗色模式，搜索

### 预期结果

文字黑色应该形成高对比度，或者至少显示清晰

### 电脑操作系统

 MacOS

### 浏览器

Chrome

### 版本

120.0.6099.129（正式版本） (arm64)

### 移动端设备

Android 小米 10 ipad 12.9 inch

### 移动端操作系统

miui

**Comment by bianyukun1213** [comment]
可能不是主题自身的问题，看起来是注入的什么东西改变了样式，把 `--fourth-text-color` 改了。

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/24708556/3fd58be4-0a8d-4a78-b70d-e0d2859efb79)

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/24708556/db57c028-33fb-454b-926a-8ea94acee9ae)

**Comment by DarkFlameMasterDev** [comment]
> 可能不是主题自身的问题，看起来是注入的什么东西改变了样式，把 `--fourth-text-color` 改了。
> 
> ![image](https://private-user-images.githubusercontent.com/24708556/294728508-3fd58be4-0a8d-4a78-b70d-e0d2859efb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjYxOTksIm5iZiI6MTcwNDc2NTg5OSwicGF0aCI6Ii8yNDcwODU1Ni8yOTQ3Mjg1MDgtM2ZkNThiZTQtMGE4ZC00YTc4LWI3MGQtZTBkMjg1OWVmYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAyMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZmNlOGZjYWY2ZjRjYmFmNzRkYTUwMzU3NzZjOTRkMzQxODI2N2FiOWM0MGU0OWRmN2JiM2FhNTM0ODI5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAZ-KX91N-769AxRoVKw-Crv60KiXuLt0goLEG-1Ip8)
> 
> ![image](https://private-user-images.githubusercontent.com/24708556/294728523-db57c028-33fb-454b-926a-8ea94acee9ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjYxOTksIm5iZiI6MTcwNDc2NTg5OSwicGF0aCI6Ii8yNDcwODU1Ni8yOTQ3Mjg1MjMtZGI1N2MwMjgtMzNmYi00NTRiLTkyNmEtOGVhOTRhY2VlOWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAyMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZjMzNzJhMGY1YTZjMjVkN2I1NmU3ZWRiYjI3MWJiODg0ZTZjZWU0Njg0YjdiN2YzNmZjNzNlNmQzN2Y1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLUhHcl5KxjeLUak-bgfgrFyxg0H-l6j1KERv5C0A9s)
> 
> 编辑：这个是在您的站点截的图。我没遇到过这样的问题。

you are right! I have fixed!
