### ISSUE TITLE
[建议] 优化一下首页文章下日期显示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#33]
希望能优化一下首页文章下日期显示，可以设置为如“2022-12-23”而不是"1天前"

**Comment by EvanNotFound** [comment]
我觉得这个无伤大雅，因为打开文章就能看见具体日期了

**Comment by EvanNotFound** [comment]
下一版本，已经在dev分支更新了

**Comment by EvanNotFound** [comment]
已在 `v0.5.0` 版本修复，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v0.5.0) 更新
