### ISSUE TITLE
[功能建议]：自动替换本地资源为对象储存链接

### ISSUE THREAD

**Issue by dzvision** [EvanNotFound/hexo-theme-redefine#333]
### 功能描述

目前我们都是通过Git提交给GitHub托管，然后利用无服务函数计算的方式例如Vercel/Netlify等方式将代码build成静态页面。我想可不可以在我们自己的md文章上，用的是本地路径，例如指向source/images/aaa.png 保存，并上传到github上。然后Vercel从GitHub同步后，基于配置文件，自动将source/images/aaa.png使用AccessKey上传到对象储存并替换掉我们的页面？这样，在GitHub上，我们永远有本地版，而实际网站上，则可以是对象存储版，更快的速度，也可以防盗链。

**Comment by EvanNotFound** [comment]
目前没有计划主题内置此功能，因为这个功能依赖其他 npm 包，但是主题不能用 npm 内嵌其他 library。

此功能不难实现，可以自行写。
