### ISSUE TITLE
[提议] 将项目许可证从 AGPL-3.0 更改为 GPL-3.0

### ISSUE THREAD

**Issue by EvanNotFound** [EvanNotFound/hexo-theme-redefine#339]
## 前言

目前本项目使用的是 [AGPL-3.0 License](https://www.gnu.org/licenses/agpl-3.0.en.html)

AGPL 对主题用户作了很大的限制，比如强制后端开源等。为了更好地维护开源社区，本人故在此征求各位 Contributor 的许可，将项目 License 更改为 GPL-3.0。

请各位被 Mention 提到的主题贡献者进行评论，决定是否更改，感谢支持。

---

The current project is licensed under the [AGPL-3.0 License](https://www.gnu.org/licenses/agpl-3.0.en.html).

The AGPL imposes significant limitations on users, including the requirement to open-source the backend code. To better support the open-source community, I propose changing the project's license to GPL-3.0.

I'm reaching out to all mentioned contributors for your input on this change. Thank you for your support.

## 主题贡献者

以下为主题在更改为 AGPL-3.0 之后对项目作出贡献的贡献者，请评论表达是否同意更改主题许可证。

- [x] @EvanNotFound 
- [x] @Ching367436
- [x] @Krazyu 
- [x] @anzai249 
- [ ] @oXnMe 
- [ ] @jiangwen5945 
- [ ] @RayAlto 
- [ ] @shawn0915 
- [ ] @DwGoing 
- [ ] @Freshwlnd

**Comment by Krazyu** [comment]
同意更改主题许可证。

**Comment by Ching367436** [comment]
同意將項目許可證從 AGPL-3.0 更改為 GPL-3.0

**Comment by anzai249** [comment]
同意更改许可证。

**Comment by Freshwlnd** [comment]
同意更改主题许可证。
