### ISSUE TITLE
[建议] 优化Waline在主题黑暗模式下的显示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#34]
希望优化一下Waline在主题黑暗模式下的显示

**Comment by EvanNotFound** [comment]
waline已经有黑夜模式了啊

<img width="1088" alt="Screen Shot 2022-12-23 at 11 44 58 PM" src="https://user-images.githubusercontent.com/68590232/209421767-62cfd416-3104-41c1-bfb9-8d311a4983fe.png">

**Comment by EvanNotFound** [comment]
Redefine 主题 `v0.4.5` 已优化，请前往 [Release页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v0.4.5) 查看
