### ISSUE TITLE
[功能建议]：更新 CDN endpoint

### ISSUE THREAD

**Issue by FreshP0325** [EvanNotFound/hexo-theme-redefine#347]
### 功能描述

移除：[staticfile](https://github.com/staticfile/static/issues/677), [bootcdn](https://www.sov2ex.com/?q=bootcdn&version=1.0.1)

新增：[sustech](https://mirrors.sustech.edu.cn/help/cdnjs.html), [zstatic](https://www.zstatic.net/services/)

两者均同步 cdnjs 库

建议移除对 staticfile 的默认支持，更换为南方科技大学长期维护的镜像站点

**Comment by famousprince** [comment]
https://github.com/EvanNotFound/hexo-theme-redefine/blob/a928d9a16c1350be7c8b52aed15bc90d1bdb7b11/scripts/helpers/themeHelpers.js#L219

Protocol duplicated, we should remove that `https:`.
