### ISSUE TITLE
[BUG] npm install nodejieba@2.5.2 安装错误

### ISSUE THREAD

**Issue by wkk-dev** [EvanNotFound/hexo-theme-redefine#355]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

Node版本 18/20 hexo 7.1.0 主题版本2.6.1
操作系统 Windows11 Git版本2.44.0

npm install nodejieba@2.5.2 时报错如下
$ npm install nodejieba@2.5.2
npm ERR! code 1
npm ERR! path C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute ‘C:\Program Files\nodejs\node.exe C:\Users\ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108’ (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@18.19.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for “C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release\nodejieba.node” (not found)
npm ERR! node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@18.19.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@18.19.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@18.19.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at “C:\Python312\python.exe”
npm ERR! gyp http GET https://nodejs.org/download/release/v18.19.1/node-v18.19.1-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.19.1/node-v18.19.1-headers.tar.gz failed, reason: read ECONNRESET
npm ERR! gyp ERR! stack at ClientRequest. (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack at ClientRequest.emit (node:events:517:28)
npm ERR! gyp ERR! stack at _destroy (node:_http_client:882:13)
npm ERR! gyp ERR! stack at onSocketNT (node:_http_client:902:5)
npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command “C:\Program Files\nodejs\node.exe” “C:\Users\ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js” “configure” “–fallback-to-build” “–module=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release\nodejieba.node” “–module_name=nodejieba” “–module_path=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release” “–napi_version=9” “–node_abi_napi=napi” “–napi_build_version=0” “–node_napi_label=node-v108”
npm ERR! gyp ERR! cwd C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba
npm ERR! gyp ERR! node -v v18.19.1
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute ‘C:\Program Files\nodejs\node.exe C:\Users\ADMIN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release\nodejieba.node --module_name=nodejieba --module_path=C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108’ (1)
npm ERR! node-pre-gyp ERR! stack at ChildProcess. (C:\Users\ADMIN\Desktop\redefine\node_modules@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22631
npm ERR! node-pre-gyp ERR! command “C:\Program Files\nodejs\node.exe” “C:\Users\ADMIN\Desktop\redefine\node_modules\@mapbox\node-pre-gyp\bin\node-pre-gyp” “install” “–fallback-to-build”
npm ERR! node-pre-gyp ERR! cwd C:\Users\ADMIN\Desktop\redefine\node_modules\nodejieba
npm ERR! node-pre-gyp ERR! node -v v18.19.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\ADMIN\AppData\Local\npm-cache_logs\2024-03-22T14_15_43_681Z-debug-0.log

望作者赶快回复/修复

### 截图

<img width="960" alt="Snipaste_2024-03-22_22-22-10" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/d49e90aa-8852-4121-ad83-959ca915fd3e">
<img width="960" alt="Snipaste_2024-03-22_22-22-25" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/6b3b2278-0a1c-49a2-84cf-0021797b02eb">
<img width="960" alt="Snipaste_2024-03-22_22-22-31" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/c65794b5-36ab-43f6-b69f-eaf6bc55ef1c">

### 电脑操作系统

Windows 11

### 浏览器

Microsoft Edge

### 版本

122.0.2365.92 X64 位

### 移动端设备

Android 13

### 移动端操作系统

MIUI 14

### 浏览器

Microsoft Edge

### 版本

122.0.2365.92

**Comment by FrederickAsYou** [comment]
尝试使用 `npm install nodejieba@2.6.0` 安装新版本nodejieba看看

**Comment by wkk-dev** [comment]
似乎卡在这里了


<img width="960" alt="wwwwwwwwwwwwSnipaste_2024-04-04_17-50-43" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/5b750379-0e42-4e02-bc1b-b2bd4774c932">

**Comment by FrederickAsYou** [comment]
安装完了吗

**Comment by FrederickAsYou** [comment]
我macOS装了2.5.2安装试过了，但是部署的时候报错，就换成了2.6.0

**Comment by wkk-dev** [comment]
不行啊，还是同样的问题

**Comment by FrederickAsYou** [comment]
你要不把redefine-demo仓库打包下载下来然后改配置试试

**Comment by FrederickAsYou** [comment]
nodejieba写的很烂

**Comment by wkk-dev** [comment]
look 
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/b14a1117-7701-4c3e-8aaa-4d8014403fe0)

**Comment by FrederickAsYou** [comment]
看起来没啥问题，你去加evan微信问问

[me.ohevan.com](https://me.ohevan.com)

**Comment by wkk-dev** [comment]
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/e9d4267d-83bc-4bf7-b060-59cc996c014c)

**Comment by FrederickAsYou** [comment]
搜索 `evanovation`

**Comment by wkk-dev** [comment]
o

**Comment by EvanNotFound** [comment]
网络问题

**Comment by FrederickAsYou** [comment]
> 网络问题

但是我Windows之前也是同样的报错，换mac之后为啥就可以装

**Comment by wkk-dev** [comment]
> ![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/e9d4267d-83bc-4bf7-b060-59cc996c014c)
> 
它是指这个问题

**Comment by FrederickAsYou** [comment]
> > ![image](https://private-user-images.githubusercontent.com/159266689/319627945-e9d4267d-83bc-4bf7-b060-59cc996c014c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzgzNTIsIm5iZiI6MTcxMjQ3ODA1MiwicGF0aCI6Ii8xNTkyNjY2ODkvMzE5NjI3OTQ1LWU5ZDQyNjdkLTgzYmMtNGJmNy1iMDYwLTU5Y2M5OTZjMDE0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODIwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmQ2MzEwNmQ0ZTAyYzg0Mzc5MTM4ZTVhNDQ0N2VmY2Y4ZWUwNjU4NDY2ODc1MWYxOGMyODI5OWMzNzc2NzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFWz312uB-WvLHFaLwIu2YSbAGoHMMZNVAu8byb3rSM)
> 
> 它是指这个问题

666
