### ISSUE TITLE
[功能建议]：建议将waline的文章反应功能加进来

### ISSUE THREAD

**Issue by FrederickBun** [EvanNotFound/hexo-theme-redefine#359]
### 功能描述

目前的waline只是评论，但waline还有一个东西叫 `文章反应` ，它可以使作者和读者之间有更多互动，建议加上

### 图片描述

<img width="822" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/120368045/63d5d2a4-5c52-4f10-bd68-36b1bdc01ab6">

### 其他

waline已经内置，只需要在 `_config.redefine.yml` 中新增这个配置就行了

**Comment by FrederickAsYou** [comment]
> ### 功能描述
> 目前的waline只是评论，但waline还有一个东西叫 `文章反应` ，它可以使作者和读者之间有更多互动，建议加上
> 
> ### 图片描述
> <img alt="image" width="822" src="https://private-user-images.githubusercontent.com/120368045/319619029-63d5d2a4-5c52-4f10-bd68-36b1bdc01ab6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyODgwMDcsIm5iZiI6MTcxMjI4NzcwNywicGF0aCI6Ii8xMjAzNjgwNDUvMzE5NjE5MDI5LTYzZDVkMmE0LTVjNTItNGYxMC1iZDY4LTM2YjFiZGMwMWFiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwMzI4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmUwYzY5MmJmNzQxNmZjN2MzZGZlMjEwNjQ0NjE0ODEwNWJlNTljMGU0YjEyNzYyNjA0NGEwMWEzYTVkNzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l6E2ybMN3RxGmY8jtO6_zgqkgQrYfvY9NMDJsk105xw">
> ### 其他
> waline已经内置，只需要在 `_config.redefine.yml` 中新增这个配置就行了

这里说错了，第一句话应该改成Redefine内置的waline只有评论功能

**Comment by FrederickBun** [comment]
参考如下：
```js
reaction: [
    'https://unpkg.com/@waline/emojis@1.1.0/weibo/weibo_heart_eyes.png',
    'https://unpkg.com/@waline/emojis@1.1.0/weibo/weibo_dog_joy.png',
    'https://unpkg.com/@waline/emojis@1.1.0/weibo/weibo_dog_consider.png',
    'https://unpkg.com/@waline/emojis@1.1.0/weibo/weibo_sob.png',
  ],
```

**Comment by FrederickBun** [comment]
已在2.6.3解决
