### ISSUE TITLE
[功能建议]：添加“工具”页面模板

### ISSUE THREAD

**Issue by FrederickBun** [EvanNotFound/hexo-theme-redefine#364]
### 功能描述

~~哈哈，我又来了~~

看到了`hexo-theme-keep`上的工具页面，也想Redefine加一个这样的模板（keep主题文档并没有这个模板）

链接：[https://xpoet.cn/tools/](https://xpoet.cn/tools/)

### 图片描述

<img width="1470" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/120368045/57a7961c-62f9-4f5c-968b-3ca2e5e2cbab">

### 其他

看evan的发挥了 ~~（最近很忙是不是？）~~

**Comment by EvanNotFound** [comment]
已在 64f8cc17d7027d645705797579e922016767b4f7 添加，下一版本更新
