### ISSUE TITLE
用Github Actions部署可以安装nodejieba

### ISSUE THREAD

**Issue by wkk-dev** [EvanNotFound/hexo-theme-redefine#375]
经测试，使用linux安装是可行的，也可以用github actions,例如 
VSCode(git推送)→github (存储)→github action (拉取编译)→action (构建部署)→(静态托管)
亲测可行![如图](https://github.com/EvanNotFound/hexo-theme-redefine/assets/159266689/b5be222f-cc92-45dd-9b3e-a14896343cd6)
[我的博客](https://blog.wkk-dev.top/)

过去问题[#335](https://github.com/EvanNotFound/hexo-theme-redefine/issues/355)

**Comment by FrederickBun** [comment]
@EvanNotFound 你要不置顶一下

**Comment by EvanNotFound** [comment]
[nodejieba](https://github.com/yanyiwu/nodejieba) 已更新到 v3，目前最新版本 node 无安装问题。
