### ISSUE TITLE
自定义头像和logo默认的图片被覆盖

### ISSUE THREAD

**Issue by attson** [EvanNotFound/hexo-theme-redefine#38]
![image](https://user-images.githubusercontent.com/119783163/210198985-0951f7cd-e4db-4e1e-9aa5-83e38d9bf17a.png)

这是主题代码里面的images，如果在自己的博客项目中 source/images 添加同名文件，会被主题库的覆盖。（这个覆盖行为应该是hexo 框架自身的逻辑？）

如下：

![image](https://user-images.githubusercontent.com/119783163/210199079-cd06a868-ee8a-49ba-82ee-bf59bba3471a.png)

建议主题库 images 使用其他的路径，或者在文档中说明一下这些文件名被占用。

```
{
    "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-searchdb": "^1.4.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-redefine": "^0.4.5"
  }
}
```

**Comment by EvanNotFound** [comment]
将在下一版本改进

**Comment by EvanNotFound** [comment]
已在 `v0.4.6` 版本修复，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v0.4.6) 更新
