### ISSUE TITLE
[Feature Request]: Providing an Interface to Change the Theme of Code Segment Syntax Coloring

### ISSUE THREAD

**Issue by 1chooo** [EvanNotFound/hexo-theme-redefine#380]
### Describe Your Idea

As the title suggests, we would like to offer different themes to change the syntax colors of code segments. This way, everyone can customize their settings according to their preferences. If needed, I can also help figure out how to add this feature. However, I may first need to understand how the current syntax coloring is set up. Thank you.

### The current syntax:

![Screenshot 2024-06-17 at 1 24 25 AM](https://github.com/EvanNotFound/hexo-theme-redefine/assets/94162591/7bc22d78-67d2-461b-9b38-9ca017963dbf)

### expected:

Maybe we can support the GitHub Theme

![Screenshot 2024-06-17 at 1 25 20 AM](https://github.com/EvanNotFound/hexo-theme-redefine/assets/94162591/c8ef53ac-075b-4a26-990c-fa4ec87c163a)

**Comment by EvanNotFound** [comment]
新版本已添加自定义 Highlightjs 代码高亮选项，已支持以下几个主题

**Light:** github, atom-one-light, default
**Dark:** github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate

请等待新版本发布

**Comment by EvanNotFound** [comment]
主题 `v2.7.0` 已发布，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
