### ISSUE TITLE
[BUG] Recommend post 跳转链接时没有带上网站域名，只有路径

### ISSUE THREAD

**Issue by FrederickBun** [EvanNotFound/hexo-theme-redefine#392]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

“文章推荐”板块中点击任意一篇推荐文章都只会在地址栏中显示路径（我讲不清楚，看下面的视频）
对主题源码初步审查觉得应该不是主题问题
[主题对应源码](https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/scripts/helpers/articleRecommend.js#L172-L175)
上方为本人所检查的代码部分，没有问题，且目前只有本站出现该问题
又检查了网站域名在yml中的配置，也没有问题
<img width="887" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/120368045/2891cfb1-c3b3-4b22-a913-314a6f10b6e6">
且该问题在2.5.2时已经发生（本站搭建好就有）

### 复现方法

点击推荐文章中的任意一篇文章

### 预期结果

跳转链接应该带上网站域名

### 截图

https://github.com/EvanNotFound/hexo-theme-redefine/assets/120368045/99b22125-8538-488e-9e86-2d78868a47b7

### 电脑操作系统

macOS 15.2

### 浏览器

Arc(Chrome内核)

### 版本

126.0.6478.127(Chromium)

### 其他

不排除有nodejiaba与nodejs的版本问题

**Comment by FrederickBun** [comment]
@EvanNotFound 视频部分注意看底部的跳转链接

**Comment by EvanNotFound** [comment]
网站配置里面 url 最后不要加 `/`

**Comment by RyouSY** [comment]
你最新的那篇文章，点进去之后刷新会直接触发下载 😂

**Comment by FrederickBun** [comment]
> 你最新的那篇文章，点进去之后刷新会直接触发下载 😂

我也很想知道为什么🤦

**Comment by FrederickBun** [comment]
> 网站配置里面 url 最后不要加 `/`

问题依然存在

**Comment by FrederickBun** [comment]
尝试切换nodejieba与nodejs版本，均无效，博客链接setbun.com

**Comment by CX330Blake** [comment]
我的網站沒有出現問題，[網站連結](https://cx330.tw)。以下是我的配置文件
```yaml
info:
    # Site title
    title: CX330's Universe
    # Author name
    author: CX330
    # Site URL
    url: https://cx330.tw
```

**Comment by FrederickBun** [comment]
解决了
