### ISSUE TITLE
[功能建议]：加入Logo字体自定义的选项

### ISSUE THREAD

**Issue by hongjr03** [EvanNotFound/hexo-theme-redefine#398]
### 功能描述

如题，加入 banner 和 sidebar 处 logo 字体自定义的选项

### 图片描述

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/64763790/afe7af0e-ed8d-49c7-b18c-fb35172f11ca)

**Comment by EvanNotFound** [comment]
主题 `v2.7.0` 已发布，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
