### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ped-Yc** [EvanNotFound/hexo-theme-redefine#399]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

更新版本后头部横幅空白，背景页无效

### 复现方法

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/33318845/525bcf0b-4106-4386-8f74-909eee00e75e)
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/33318845/791c38fe-f8f6-4f4c-879a-059364af51f4)
![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/33318845/c85e68c4-450a-4bae-9776-da7ba806056c)

### 预期结果

本来应该显示设置的背景页

### 浏览器

edge

**Comment by FrederickBun** [comment]
<img width="1159" alt="image" src="https://github.com/EvanNotFound/hexo-theme-redefine/assets/120368045/6ef568fb-7052-490b-ab92-d4ce110585cb">

访问时未出现问题

**Comment by EvanNotFound** [comment]
未出现问题，无法复现

![image](https://github.com/EvanNotFound/hexo-theme-redefine/assets/68590232/d9b339ef-f55d-4403-a973-025447e3d5a5)
