### ISSUE TITLE
[BUG] 文章加密与 Swup 冲突导致部分 js 无法正常调用

### ISSUE THREAD

**Issue by LynxCatTheThird** [EvanNotFound/hexo-theme-redefine#400]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [~~如果刚更新完主题出现此问题，~~ 已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

https://github.com/LynxCatTheThird/web-v6/blob/main/_config.redefine.yml
https://github.com/LynxCatTheThird/web-v6/blob/main/_config.yml
网站：https://web-v6-tester.vercel.app/ ，文章密码 114514
疑似文章加密与 Swup 冲突导致部分 js 无法正常调用，进一步引起部分页面不渲染。

### 复现方法

1. `_config.redefine.yml` 中 `single_page: true`
2. `post1.md` 中 `password: 114514`
3. `hexo server`
4. 从 Home 中点入 `post1`
5. 发现代码框没有复制按钮、Mermaid 未正常渲染

### 预期结果

输入密码后这些 js 能够正常运行，并渲染出页面。

### 截图

![image](https://github.com/user-attachments/assets/2cefb25d-bcf3-401f-9b35-18e8df8dbe27)
![image](https://github.com/user-attachments/assets/f31b79c4-1b4e-43f4-9c8b-e7039f4cc60b)

### 电脑操作系统

ArchLinux

### 浏览器

Google Chrome

### 版本

126.0.6478.126（正式版本）

**Comment by angelop007** [comment]
我这边是输入密码后，自动打开了页面，然后页面还是提示需要输入密码

**Comment by EvanNotFound** [comment]
主题 `v2.7.0` 已发布，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
