### ISSUE TITLE
询问一下HEXO主题的一些问题

### ISSUE THREAD

**Issue by f-dong** [EvanNotFound/hexo-theme-redefine#401]
作者你好，我是另一款 [简陋主题](https://github.com/f-dong/hexo-theme-minimalism) 的开发者，最近在 hexo 版本更新到 7.2.0 以后，主题代码高亮中的 prismjs 便失效了，我因个人原因没太多时间详查问题原因，请问您是否遇到了相同问题，如果有还望告知一下解决方案，感谢不吝赐教

**Comment by EvanNotFound** [comment]
你好，

本主题使用的是 highlightjs，对于 prismjs 失效的问题，我建议你看一下日志，找一下为什么失效的原因。

没有日志或者任何报错的话，我也没办法帮助你
