### ISSUE TITLE
[Feature Request]: Improved encryption functionality

### ISSUE THREAD

**Issue by lfgberg** [EvanNotFound/hexo-theme-redefine#404]
### Describe Your Idea

Implement a tag such as `{% decrypt %}` that allows a portion of a post to be visible without entering the password

**Comment by EvanNotFound** [comment]
The encryption used in this theme is directly from https://github.com/D0n9X1n/hexo-blog-encrypt

Please open an issue there. I am not responsible for article encryption functionality.

Thanks
