### ISSUE TITLE
[Feature Request]: Add word-wrap for "Table of Contents"

### ISSUE THREAD

**Issue by 825i** [EvanNotFound/hexo-theme-redefine#413]
### Describe Your Idea

List items in the optional table of contents on the right side of an article should have an option to be word-wrapped.

Currently they are just truncated by an ellipses (...) if they are longer than 22 characters it seems.

### Visual Aids

Please let us word-wrap these headings in the table of contents, so they are not all truncated as shown below.

![image](https://github.com/user-attachments/assets/48874a62-6144-405c-b101-288c73e35b12)

**Comment by EvanNotFound** [comment]
It will not look good with word wrap, so I don't think it's a good idea.

Instead, you should decrease the title length.

If anything, you can reopen this issue
