### ISSUE TITLE
[Feature Request]: Longer article previews on the home screen

### ISSUE THREAD

**Issue by 825i** [EvanNotFound/hexo-theme-redefine#414]
### Describe Your Idea

The home screen limits the amount of words that can be displayed in an article preview. It should be possible for us to manually set the amount of lines/words that we want before the article text is truncated with an ellipses (...)

### Visual Aids

I should be able to (for example) display 3-5 lines of an article here if I wished, in order to grab the reader's attention in the first/opening paragraph.

![image](https://github.com/user-attachments/assets/a89cd1a6-3cbd-4789-9ee8-ebe1a6086d2f)

**Comment by FrederickBun** [comment]
Maybe it's because I used a full-corner text like Chinese, so it takes up a lot of space and reaches 3 lines

**Comment by FrederickBun** [comment]
However, if there are more English characters in my summary, only two lines will be displayed

such as:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/cbb0c168-3587-4a25-b525-c70a85a7ac85">

**Comment by FrederickBun** [comment]
> Ok thanks for the reply. I think then it would still be good to have a feature that increases the line limit in general.
> 
> BTW you have a really amazing looking site by the way. Best Hexo I have seen.

Thank you!

I'm also looking forward to this feature because it's in every other theme I've used

**Comment by EvanNotFound** [comment]
主题 `v2.7.0` 已发布，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
