### ISSUE TITLE
[BUG] Twikoo 评论不显示

### ISSUE THREAD

**Issue by blhcm** [EvanNotFound/hexo-theme-redefine#415]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

主题中 Twikoo 的 Swup 配置似乎存在问题，导致 Twikoo 评论无法正常加载。
Waline 等不存在此问题。

### 复现方法

使用 Twikoo 作为网站的评论系统

### 预期结果

正常加载评论

### 截图

![image](https://github.com/user-attachments/assets/907f663b-b602-4e29-9da1-7538d6b809c0)
https://hiraethecho.github.io/hexo/
https://www.buzhihuohuo.top/
https://xblog.aptzone.cc/
主题用户墙中多位用户的 Twikoo 评论区无法显示，需要手动刷新

**Comment by LRay-iu** [comment]
我碰到过这个问题，您可以尝试切换不常用的浏览器，如果切换浏览器显示正常的话，可以去扩展里面看一下，有可能跟插件冲突了，甚至您可以再尝试一下encrypt功能,可能会出现输入密码后没有反应的情况；
如果情况属实，您可以尝试停用一部分插件（大概率是广告拦截之类的，至少我是这样）

**Comment by EvanNotFound** [comment]
由于大多数广告屏蔽插件会自动拦截 `staticfile` CDN 域名，导致评论系统加载失败。当前主题版本（包括之前的版本）使用了 staticfile 作为 Gitalk 和 Twikoo 的脚本源。

然而，staticfile 以及 Bootcdn 由于存在 CDN 投毒的安全风险，已经不再安全。因此，主题的新版本 (2.6.5 +) 已切换到 Cloudflare 的 CDNJS 作为 Twikoo 和 Gitalk 的脚本源。

如需进一步了解相关内容，请访问 [【BootCDN/Staticfile投毒分析】供应链投毒后，我们的选择还剩下哪些？](https://www.52pojie.cn/thread-1944970-1-1.html)（来源：吾爱破解论坛）。

主题新版本 2.6.5 发布后，请及时更新主题版本，并避免使用 bootCDN 和 staticfileCDN。感谢您的理解与支持。

**Comment by EvanNotFound** [comment]
主题 `v2.7.0` 已发布，请前往更新 https://github.com/EvanNotFound/hexo-theme-redefine/releases
