### ISSUE TITLE
WARN  Check latest version failed: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Alphouse** [EvanNotFound/hexo-theme-redefine#418]
### Pre-Submission Checklist

- [X] I've run `hexo clean`, but the problem persists.
- [X] [I've updated to the latest theme version](https://redefine-docs.ohevan.com/getting-started#update)
- [X] [Post theme update, I've ensured the theme's configuration is in sync](https://redefine-docs.ohevan.com/getting-started#migrate-configuration)

### Describe the Bug

我是一位新手，当我运用主题后出现的这个问题我无法解决，应该是在这里向作者提交问题吧
运行命令后一直出现警告，
![1](https://github.com/user-attachments/assets/baea4603-0957-4b45-beaf-1bb0e3977692)
![2](https://github.com/user-attachments/assets/64ab1862-a6e2-4482-8600-a79de41b8c94)
我已经是新版本，并且本地能够正常运行，当我想使用GitHub pages尝试部署时，也出现问题。
![3](https://github.com/user-attachments/assets/71bf81b2-3d61-48b7-8444-b431ece7f69c)
由于个人水平问题，没能在网上找到解决办法，希望得到帮助。

### Your Computer's OS

Windows

### Which Browser?

Chrome

**Comment by FrederickBun** [comment]
使用的什么方法安装主题

**Comment by FrederickBun** [comment]
似乎是获取主题更新的 api 错误

**Comment by FrederickBun** [comment]
> 似乎是获取主题更新的 api 错误

从状态页面看，api 并未出现下线状态

请检查网络，还请给出详细 GitHub 报错信息

**Comment by FrederickBun** [comment]
> 使用的什么方法安装主题

如果使用的 Git，建议切换 npm 会解决一部分部署时找不到主题的问题

**Comment by Alphouse** [comment]
根据“快速开始”中的git我无法连接，所以通过github下载库文件，然后按照指南进行

**Comment by FrederickBun** [comment]
是因为 git 项目嵌套了 git 项目

**Comment by Alphouse** [comment]
所以是建议重新使用npm下载？

**Comment by FrederickBun** [comment]
是的

**Comment by FrederickBun** [comment]
然后将你手动下载的文件全部删除

**Comment by FrederickBun** [comment]
进展如何？

**Comment by Alphouse** [comment]
首先谢谢你的帮助，但我在使用npm进行安装时出现了新的麻烦。
![4](https://github.com/user-attachments/assets/3abffcb0-c4c2-41f5-a0c5-d5335c1e0d5f)
git显示应该没问题，但是文件夹中没有新增主题文件。
当我想要重新开始部署时，又遇到了这个问题
![5](https://github.com/user-attachments/assets/c6b038e9-55c9-44d4-9a95-2cb5a3873d16)
之前遇到，但我忘记怎么解决了。

**Comment by FrederickBun** [comment]
为什么要重新init一个呢

**Comment by Alphouse** [comment]
我猜测是我的hexo出现了问题导致npm安装失败

**Comment by FrederickBun** [comment]
直接在博客根目录安装主题就可以了啊

**Comment by Alphouse** [comment]
我使用了npm进行安装，但结果还是出现worn
![6](https://github.com/user-attachments/assets/4ad6b9b6-fb94-4f0b-a785-66624016bb84)

**Comment by EvanNotFound** [comment]
warn 只是警告，说的只是你网络问题无法连接到主题更新 api 没法检测新版本，无需理会，可以正常使用主题

**Comment by Alphouse** [comment]
我想要通过github pages进行部署，过程中一直出现报错
![9](https://github.com/user-attachments/assets/4dc9d730-a808-4d03-8fc4-7a7c88fbd676)
这个问题我没有找到方法去处理，文件上传到了我的库中可以帮忙看一下吗

> warn 只是警告，说的只是你网络问题无法连接到主题更新 api 没法检测新版本，无需理会，可以正常使用主题

**Comment by FrederickBun** [comment]
查看了详细信息，发现你用 jekyll 部署的啊

**Comment by FrederickBun** [comment]
https://hexo.io/zh-cn/docs/github-pages

查看此文档部署

**Comment by Alphouse** [comment]
谢谢你的帮助，问题已经解决了
