### ISSUE TITLE
[功能建议]：添加 artalk 评论系统

### ISSUE THREAD

**Issue by FrederickBun** [EvanNotFound/hexo-theme-redefine#419]
### 功能描述

添加 artalk 评论

https://artalk.js.org

### 图片描述

![image](https://github.com/user-attachments/assets/4103e465-5652-498b-9437-ebee2453e28d)

**Comment by EvanNotFound** [comment]
![CleanShot 2024-08-31 at 11 42 29@2x](https://github.com/user-attachments/assets/71d48a54-c322-43e4-bc02-3051aacb8cfb)

artalk 自身官网评论系统都出问题。稳定了以后再考虑添加

**Comment by FrederickBun** [comment]
似乎部分用户的网络问题，我这边正常，但是确实在某些方面有 bug，可以后面考虑
