### ISSUE TITLE
[功能建议]：关闭开屏的缓冲动画

### ISSUE THREAD

**Issue by negkol** [EvanNotFound/hexo-theme-redefine#420]
### 功能描述

在配置文件中加一个可以选择是否开启开屏的缓冲动画的选项

**Comment by FrederickBun** [comment]
有的

**Comment by FrederickBun** [comment]
在主题配置中的 `global.preloader` 中修改

第 `82` 行左右

<img width="358" alt="image" src="https://github.com/user-attachments/assets/4ca545f3-3e9c-48b6-9473-b44b6ad60c11">

**Comment by negkol** [comment]
请问在哪 @FrederickBun

**Comment by FrederickBun** [comment]
主题配置文件的第 82 行左右的位置

**Comment by FrederickBun** [comment]
Duplicate of #340

**Comment by negkol** [comment]
谢谢

**Comment by FrederickBun** [comment]
没事

**Comment by negkol** [comment]
这个能删掉吗qwq

**Comment by FrederickBun** [comment]
额，这个我回答不了

**Comment by FrederickBun** [comment]
改了配置也不影响，可能到时候找个地方更新一下文档就可以了

**Comment by negkol** [comment]
嗯嗯，我看 https://redefine-docs.ohevan.com/basic/global 上没有这个，请有时间加上去吧

**Comment by FrederickBun** [comment]
在写呢

**Comment by EvanNotFound** [comment]
文档已添加，感谢 @FrederickBun。主题下一版本将默认关闭缓冲动画。
