### ISSUE TITLE
[功能建议]：暗色模式下的行内代码块背景颜色与网页背景色过于接近

### ISSUE THREAD

**Issue by LAST7** [EvanNotFound/hexo-theme-redefine#428]
### 功能描述

希望暗色模式下，行内代码块背景颜色能够更有区分度一些（提高/降低明度）

### 图片描述

亮色模式下的小代码块：

![Shot-2024-09-04-004132](https://github.com/user-attachments/assets/0fb136a8-2370-4857-a2dc-43cea356d022)

暗色模式：

![Shot-2024-09-04-004153](https://github.com/user-attachments/assets/31174b89-542a-4347-a3b9-7d064b5b667e)

可以看到，在暗色模式下，除去字体变化外几乎看不出来行内代码块的样式。

### 其他

感谢 Evan 和其他 contributer 创作和维护的主题，好看又好用 :)

**Comment by EvanNotFound** [comment]
v2.7.1 已更新 / 修复此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新
