### ISSUE TITLE
[BUG] ：行内代码样式丢失或几乎不可见

### ISSUE THREAD

**Issue by lhtstudy** [EvanNotFound/hexo-theme-redefine#429]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

更新到最新版本后出现行内代码样式丢失或者几乎不可见的问题，降级回 2.6.4 版本后恢复正常
2.7.0
![image](https://github.com/user-attachments/assets/9c7eb2a3-be71-4b41-bf97-0f7abf8a25d0)
2.6.4
![image](https://github.com/user-attachments/assets/4b3f8647-a499-486a-8ae3-25b660d688ba)

### 电脑操作系统

Windows

### 浏览器

Edge

### 版本

128.0.2739.54 (Official build) (64-bit)

**Comment by EvanNotFound** [comment]
v2.7.1 已更新 / 修复此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新
