### ISSUE TITLE
[BUG] Github Page 页面下的站点 logo 显示大小过大

### ISSUE THREAD

**Issue by CatIsNotFound** [EvanNotFound/hexo-theme-redefine#438]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

博客网站的站点 logo 在本地预览下能够正常显示其大小，然而在 Github Page 页面下显示的站点 logo 大小过大。对比图见截图。
PS: 已尝试重新创建博客存档以及安装主题，但问题依旧

### 截图

![question1](https://github.com/user-attachments/assets/f8db7c8e-42c7-496b-ba0b-f37bb1ca8271)

### 电脑操作系统

Windows

### 浏览器

Chrome

### 版本

129

**Comment by EvanNotFound** [comment]
Redefine v2.7.2 已更新 / 修复此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新。
