### ISSUE TITLE
[功能建议]：对行间公式块的优化

### ISSUE THREAD

**Issue by Burnling-gx** [EvanNotFound/hexo-theme-redefine#439]
### 功能描述

在本地编辑器中，行间公式换行使用 `\\`
但是部署之后， `\\` 会被转义成一个单 `\`
为了保证部署后公式正常换行，在本地不得不使用 `\\\\` 来换行，但就导致文章在本地看起来非常丑陋。

所以能否优化一下，使得在 mathjax 渲染前，redefine 将 `\\` 转化成 `\\\\` 来保留换行信息呢？

**Comment by EvanNotFound** [comment]
redefine 对 markdown 内容没有控制，这些都是 hexo 博客框架处理的，主题只是增加一些样式。

主题无法负责 mathjax 插件。抱歉
