### ISSUE TITLE
[功能建议]：希望兼容hexo-theme-keep v4.1.0支持的页面模板tools（工具） 

### ISSUE THREAD

**Issue by DuAn320** [EvanNotFound/hexo-theme-redefine#440]
### 功能描述

keep主题文档链接：https://keep-docs.xpoet.cn/advanced/page-template.html#tools-%E5%B7%A5%E5%85%B7

### 图片描述

![image](https://github.com/user-attachments/assets/dfe6f911-7691-4fe5-8440-c8cddd592bcd)

**Comment by xzadudu179** [comment]
#364

**Comment by EvanNotFound** [comment]
已在 64f8cc17d7027d645705797579e922016767b4f7 添加，下一版本更新
