### ISSUE TITLE
[BUG] Hexo Counter Causing Google Meet Video Lag + Webcam Crashing on Brave

### ISSUE THREAD

**Issue by 825i** [EvanNotFound/hexo-theme-redefine#444]
### 提交 Issue 前检查清单

- [ ] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

I have found an extremely odd bug.

When I have a tab of any page of my blog open and focused (post, page, homepage, anything). My Webcam video in another tab/window for Google Meets, will start to lag every 1 second. The audio is fine, but my own video will start lagging for myself and everyone else watching me.

I believe that this is caused by the ticker/counter at the bottom of the page, that counts uptime every 1 second.

![{1A5BD5C5-E61E-41B8-B1F0-4D49D38B6096}](https://github.com/user-attachments/assets/0555d23e-6e0e-4d2f-a1b8-e93469256f56)

Another reason why I believe it is this counter, is because as soon as I stop focusing on this tab and it goes into the background. The lag stops immediately. It only lags my webcam when the tab is actually open and is the active focused tab. It does not matter however if I am looking at the counter, just as long as the counter is on the page counting, even if I am at the top of a blog page. However, the lag is definitely even worse if I scroll down and actually look at the counter.

I would recommend to check/remove/rewrite the counter in such a way that it does not cause this lag in other windows. It seems more likely that this is actually a GPU problem and not a CPU problem. As this seems to interfere with video and nothing else. It also seems likely looking at Task Manager and seeing the GPU cycle calls.

_CPU: Ryzen 7800X3D
RAM: 32GB DDR5 6GHz
GPU: RTX 4090
SSD: WD_BLACK 1TB
So I should not at all have any lag with these specs._

Furthermore, the webcam can completely crash in Google Meets and disconnect when refreshing the blog page.

You can also test this yourself.

1. Open a new Google Meets window and turn on Webcam.
2. Then open a blog with this counter on it.
3. Keep the blog open in another focused window.
4. Webcam immediately starts to lag.
5. Close the window/tab with the blog page and the lag instantly stops.

### 电脑操作系统

Windows 11

### 浏览器

Brave

### 移动端设备

PC

### 浏览器

Brave

**Comment by EvanNotFound** [comment]
I cannot reproduce.

Device:
Apple Macbook Pro M1 Pro
16GB 512GB

Please try using a different browser, and test on other computers/laptops. Everything works fine for me.
