### ISSUE TITLE
[BUG] 行内公式错误渲染成行间公式

### ISSUE THREAD

**Issue by Gypsophila-cx** [EvanNotFound/hexo-theme-redefine#447]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

v2.7.2版本成功修复了问题#442中提到的较长的行间公式出现遮挡的问题，但是同时导致目前所有端的行内公式全部变成了行间公式。

### 复现方法

使用 $ formula $ 写一个行内公式，网页渲染后将发现它自动变为了行间公式。

### 预期结果

 $ formula $ 应当渲染得到行内公式，$$ formula $$ 应当得到行间公式。

### 截图

<img width="842" alt="屏幕截图 2024-10-27 231152" src="https://github.com/user-attachments/assets/cee39d60-e078-4ed2-9d36-469e66a7261f">

### 电脑操作系统

Windows

### 浏览器

Chrome

### 移动端设备

ipad pro, Xiao mi

### 浏览器

Chrome

**Comment by EvanNotFound** [comment]
v2.7.3 已更新 / 修复此功能，请前往 [Release 页面](https://github.com/EvanNotFound/hexo-theme-redefine/releases) 更新。
