### ISSUE TITLE
[BUG] 除了网站首页，其他页面Navbar都会内缩

### ISSUE THREAD

**Issue by Ataidawa** [EvanNotFound/hexo-theme-redefine#454]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

除了主页面（如果存在多个博客页，首页点击第二页Navbar也会向内缩）其他页面的导航栏，内容显示的宽度与主页上的不同，明显缩小。

### 复现方法

在主页时切换至其他页面

### 预期结果

navbar宽度保持不变

### 截图

![Snipaste_2024-11-15_07-12-17](https://github.com/user-attachments/assets/33537c25-24dc-46bb-80be-4c26592f4459)
![Snipaste_2024-11-15_07-12-27](https://github.com/user-attachments/assets/a03bc4f4-44ac-451c-8dd1-0bc1d279fcff)
![Snipaste_2024-11-15_07-12-33](https://github.com/user-attachments/assets/6e9c3949-86d4-4859-a4a4-5623cf88799e)

### 电脑操作系统

Windows 10

### 浏览器

Microsoft Edge

### 版本

130.0.2849.46

**Comment by EvanNotFound** [comment]
设计就是这样，导航栏太宽会影响用户专注度，所以主题文章页面导航栏会自动缩窄为文章宽度。

需要更改的话，请自行修改主题配置项 `global.content_max_width`。文档：https://redefine-docs.ohevan.com/zh/basic/global#%E6%96%87%E7%AB%A0%E6%9C%80%E5%A4%A7%E5%AE%BD%E5%BA%A6

**Comment by Ataidawa** [comment]
老师，你说的没问题，但是第一屏的第二页的导航栏是不是不应该内缩啊？
![Uploading Snipaste_2024-11-18_17-35-26.png…]()

**Comment by Ataidawa** [comment]
![Snipaste_2024-11-18_17-35-26](https://github.com/user-attachments/assets/a66c0da4-364b-4efe-9715-9f92c1c27aa7)
