### ISSUE TITLE
[BUG] '分类'(categories)和'归档'(archives)功能失效

### ISSUE THREAD

**Issue by aaronhumm-cmm** [EvanNotFound/hexo-theme-redefine#456]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

归档并未增改，只是去除了原有的注释，但点击后为404状态。

**Comment by aaronhumm-cmm** [comment]
手误提交了……
另一个内容是“分类”，正常创建了categories，并且点击分类后也能出现所有的分类，但点击最小节点的分类后则是获取失败(Cannot GET /categories/随笔/)

https://github.com/user-attachments/assets/e784e828-5171-46ba-a9f1-f8dc4970bfaa

求助求助啊

**Comment by EvanNotFound** [comment]
你 hexo 站点配置文件 _config.yml 里面的 categories 没有配置好

![image](https://github.com/user-attachments/assets/079adc73-4c13-4f02-bbca-5b0031fbb202)

**Comment by aaronhumm-cmm** [comment]
![image](https://github.com/user-attachments/assets/9c096715-dae4-461a-8074-fb163082fdbe)
不好意思，关于_config.yml文件我这里和你的是一样的，拉取下来这块就没有改过它，还是说关于这个config配置我要改成什么呢？
然后这个是_config.redefinde.yml中的分类和归档：
![image](https://github.com/user-attachments/assets/f3f7d933-0ca1-4a71-9148-036a7fcc86c8)
麻烦你了。

**Comment by EvanNotFound** [comment]
那就怪了，应该是你 hexo 配置问题。

你 `git clone` 一下主题的 demo，https://github.com/EvanNotFound/redefine-demo

然后 
```
npm install && hexo clean && hexo s
```
看一下 categories 正不正常

**Comment by aaronhumm-cmm** [comment]
是的，应该是hexo的问题，我依赖里看了，版本不是最新的同时hexo-generator-archive和hexo-generator-category的依赖也没有，可能是拉取的时候没下全。
