### ISSUE TITLE
[BUG] 链接对应的文字在页面上渲染有误

### ISSUE THREAD

**Issue by QSlotus** [EvanNotFound/hexo-theme-redefine#459]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

在markdown中，一大段文字中含有一个或几个链接即会出现此bug
如图示：
![image](https://github.com/user-attachments/assets/d648ce8e-b2f5-412e-954f-6dc00d9ac843)
![image](https://github.com/user-attachments/assets/d7180a1f-d6c2-451f-897b-0cf3a452c295)
原文：
```md
Flarum 的前身是 [esoTalk](https://github.com/esotalk/esoTalk) 和 [FluxBB](https://fluxbb.org/)， 它生来就被设计如此：
```

### 复现方法

使用最新版本Redefine主题，并且在文章中输入 一大段含有一个或几个链接的文字
可前往 https://blog.qiusyan.top/posts/27098 查看（出现问题的网址）

### 预期结果

仅渲染指定的文字

### 截图

见上文

### 电脑操作系统

Windows 10

### 浏览器

Edge

### 版本

131.0.2903.51

### 其他

发现作者的示例博客中也出现了这个问题
![image](https://github.com/user-attachments/assets/63c781c3-9a95-4bb3-b6f5-758d7e550dce)
![image](https://github.com/user-attachments/assets/80d089a4-3243-44fb-a6f3-70f10c9e3662)

网址：https://redefine.ohevan.com/2007/01/09/hello-world/

**Comment by FelixChristian011226** [comment]
> > 同样有这个问题，而且我的链接图标渲染不出来，不知道是为什么
> 
> @FelixChristian011226 链接图标不显示是因为sharp_solid组的图标没有开启，可以去配置文件里面启用一下 作者也在最新提交中默认启用了这个图标组 （[5b560df](https://github.com/EvanNotFound/hexo-theme-redefine/commit/5b560df84e0f32f250d391c73c6236d12c6edb40) ）

感谢感谢！！

**Comment by EvanNotFound** [comment]
我的问题，手贱没加 closing tag </a>
