### ISSUE TITLE
[BUG] 博客页面展示异常

### ISSUE THREAD

**Issue by Ataidawa** [EvanNotFound/hexo-theme-redefine#460]
### 提交 Issue 前检查清单

- [X] 已经尝试执行 `hexo clean`，问题仍然存在
- [X] [已经更新到主题最新版本](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [X] [如果刚更新完主题出现此问题，已经确认同步了主题配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

### Bug 描述

https://ataidawa.github.io/2024/11/14/Hexo-theme%E6%90%AD%E5%BB%BA%E8%AE%B0%E5%BD%95/

**Comment by Ataidawa** [comment]
![Snipaste_2024-11-20_18-01-48](https://github.com/user-attachments/assets/aab55681-3f0e-408a-a959-ffbc1697a495)
不小心点到了，md文件见截图 在typora中应用了redefine主题模式下显示正常，上传至网站渲染后怎么改都不正常，第4点和第5点总是会被赋予超链接

**Comment by EvanNotFound** [comment]
duplicate of #459

**Comment by Ataidawa** [comment]
按照#459中的反馈启用了sharp_solid组图标，图标正常显示 但前一行有超链接之后的缩进会全部乱掉 [懒事屋 - 辅助手册](https://ataidawa.github.io/2024/11/14/Hexo-theme%E6%90%AD%E5%BB%BA%E8%AE%B0%E5%BD%95/) 可以在这里看到异常，该异常不止存在于一处，
[Hexo-theme搭建记录.md](https://github.com/user-attachments/files/17835608/Hexo-theme.md)
提供md文件对比检查
![Snipaste_2024-11-21_03-06-52](https://github.com/user-attachments/assets/d2f4589d-aa96-44ee-9377-73c0c3dab5f3)
