### ISSUE TITLE
[BUG] aplayer开启后没有在页面显示

### ISSUE THREAD

**Issue by rxw2023** [EvanNotFound/hexo-theme-redefine#463]
### Pre-Submission Checklist

- [X] I've run `hexo clean`, but the problem persists.
- [X] [I've updated to the latest theme version](https://redefine-docs.ohevan.com/getting-started#update)
- [X] [Post theme update, I've ensured the theme's configuration is in sync](https://redefine-docs.ohevan.com/getting-started#migrate-configuration)

### Describe the Bug

aplayer:
    enable: true # Whether to enable
    type: fixed   # fixed, mini
    audios:
         。。。。。。

### Reproduction Steps

我试了之后没有出现

### Your Computer's OS

windows

**Comment by QSlotus** [comment]
你需要按照文档添加相关音频参数（音频名称，音频作者，音频直链url，音频封面）
![image](https://github.com/user-attachments/assets/0a4df974-d326-4219-ae2d-05f4b8351d47)

**Comment by rxw2023** [comment]
但是我试了在2.7.3可以， 2.8.1不行了，你可以试试

**Comment by EvanNotFound** [comment]
是bug，我今天看看

**Comment by rxw2023** [comment]
ok
