### ISSUE TITLE
[功能建议] 说说

### ISSUE THREAD

**Issue by xcx2006** [EvanNotFound/hexo-theme-redefine#52]
希望可以添加背景
如butterfly https://butterfly.js.org/
next https://rusunoi.github.io/ （我的一个同学搭的可能不太好）
的效果

**Comment by xcx2006** [comment]
前面发的是个脚本(js)效果就是点击会出现一个心

**Comment by xcx2006** [comment]
cdn速度不行
推荐一下netlify

**Comment by EvanNotFound** [comment]
> cdn速度不行 推荐一下netlify

抱歉，netlify不是有效的cdn提供商。目前cdn提供商是我自费的阿里云oss，已经开启cdn全球加速了。

unpkg和jsdelivr会更慢。如果你是用netlify部署的建议直接不要用cdn，netlify已经很快了

**Comment by EvanNotFound** [comment]
> 前面发的是个脚本(js)效果就是点击会出现一个心

这个可以通过加入自定义js脚本解决，详见：https://redefine-docs.ohevan.com/docs/configuration-guide/inject

也可以通过安装插件

**Comment by xcx2006** [comment]
可以将这个添加进来吗？我不知道怎么弄https://blog.zhheo.com/p/557c9e72.html

**Comment by EvanNotFound** [comment]
> 可以将这个添加进来吗？我不知道怎么弄https://blog.zhheo.com/p/557c9e72.html

好的，下下版本加

**Comment by ncwzdlsd** [comment]
> 可以将这个添加进来吗？我不知道怎么弄https://blog.zhheo.com/p/557c9e72.html

即刻短文其实不如用 Artitalk 部署说说界面方便🙃毕竟即刻短文是静态的，貌似 Redefine 主题对 Artitalk 说说界面适配还不错（）

**Comment by EvanNotFound** [comment]
> 

好主意

**Comment by EvanNotFound** [comment]
> > 可以将这个添加进来吗？我不知道怎么弄https://blog.zhheo.com/p/557c9e72.html
> 
> 即刻短文其实不如用 Artitalk 部署说说界面方便🙃毕竟即刻短文是静态的，貌似 Redefine 主题对 Artitalk 说说界面适配还不错（）

好主意

**Comment by xcx2006** [comment]
> > 可以将这个添加进来吗？我不知道怎么弄https://blog.zhheo.com/p/557c9e72.html
> 
> 即刻短文其实不如用 Artitalk 部署说说界面方便🙃毕竟即刻短文是静态的，貌似 Redefine 主题对 Artitalk 说说界面适配还不错（）

artitalk有时候特别慢

**Comment by xcx2006** [comment]
而且用github action可以自动部署，挺方便的

**Comment by xcx2006** [comment]
所以还是希望弄个说说

**Comment by EvanNotFound** [comment]
Redefine v1.2.0 已修复/更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.2.0 查看
