### ISSUE TITLE
[功能建议] 代码块样式建议

### ISSUE THREAD

**Issue by saddestboy** [EvanNotFound/hexo-theme-redefine#57]
simple样式代码块显示代码块标题和链接样式个人觉得似乎不是很美观……
![QQ截图20230208233148](https://user-images.githubusercontent.com/63148202/217576464-8146c3fb-c2f8-4e4f-8c25-82c17337f10e.png)
似乎把标题和链接往中间压压的话会好看一点
![QQ截图20230208233226](https://user-images.githubusercontent.com/63148202/217576774-b87ee607-217d-495c-99b8-a68742ff759d.png)

附：
![QQ截图20230208233129](https://user-images.githubusercontent.com/63148202/217576889-35de943f-daf2-417c-87d2-2b54b78c126c.png)

**Comment by EvanNotFound** [comment]
好建议，这就优化

**Comment by EvanNotFound** [comment]
Redefine v1.1.1 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.1 查看
