### ISSUE TITLE
[反馈] 首页文章下日期显示

### ISSUE THREAD

**Issue by lalalll-lalalll** [EvanNotFound/hexo-theme-redefine#60]
我在_config.redefine更改了date_format:的值为 MMM DD YYYY
可是并不起作用,文章依旧是[14 小时前]

请问我是否遗漏了什么(
![Screenshot_1](https://user-images.githubusercontent.com/69378613/218917590-f041c638-5f2a-450e-9b5d-2c28c9cc591e.png)
![Screenshot_3](https://user-images.githubusercontent.com/69378613/218917609-20a1189c-3b79-4a59-8f2a-3d9e958e90ef.png)

**Comment by EvanNotFound** [comment]
已经在 dev 分支修复，请等待下一版本

**Comment by EvanNotFound** [comment]
Redefine v1.1.2 已修复，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.2 查看
