### ISSUE TITLE
[反馈] 首页右侧工具栏

### ISSUE THREAD

**Issue by lalalll-lalalll** [EvanNotFound/hexo-theme-redefine#61]
首页右侧的工具栏在最顶部以及最底部时会隐藏
但是尽管工具栏的图标隐藏的,那个位置仍旧可以交互,点击

请原谅我没有好的图片描述这个问题...(
![Screenshot_1](https://user-images.githubusercontent.com/69378613/219054926-8874ff26-2b97-4110-b6ce-4398932fc6aa.png)
![Screenshot_3](https://user-images.githubusercontent.com/69378613/219054969-240b49a9-1d6f-4d02-a0e1-da6f53c915f2.png)

**Comment by EvanNotFound** [comment]
好的，下一版本修一下

**Comment by EvanNotFound** [comment]
Redefine v1.1.2 已修复，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.2 查看
