### ISSUE TITLE
[功能建议] markdown中代码块美化

### ISSUE THREAD

**Issue by zhaosq11** [EvanNotFound/hexo-theme-redefine#62]
请问网站中markdown的代码部分，如何修改，或者说是否支持修改？例如：
![捕获](https://user-images.githubusercontent.com/95084791/219264378-70d17d6a-5f01-4a35-ad8f-64ddb203d8c5.PNG)
这块的字体格式如何修改。

**Comment by EvanNotFound** [comment]
目前还不能自定义字体，我可以下一版本加一下这个功能

**Comment by EvanNotFound** [comment]
Redefine v1.1.2 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.2 查看
