### ISSUE TITLE
[功能建议] 插入音乐元素

### ISSUE THREAD

**Issue by zhaosq11** [EvanNotFound/hexo-theme-redefine#63]
非常抱歉，麻烦您了，咨询下，我尝试使用我自己写的音乐网站插入到Directory目录中，自己网站上的CSS和您的似乎是冲突的，会造成乱码的情况，并且我测试使用hexo-tag-aplayer也会显示出现异常情况，需要刷新后正常，是不兼容还是不支持呢？
（想将自己的音乐index直接插入到目录中）
![image](https://user-images.githubusercontent.com/95084791/219266115-397fcb2f-fc06-4244-9876-00c205275da7.png)
这似乎和我的预期不符
![image](https://user-images.githubusercontent.com/95084791/219266314-2445abd1-a047-4ab0-b5e5-92a8a8e1cb1f.png)

**Comment by EvanNotFound** [comment]
目前还没有这方面的优化，有需要的话，我下个版本可以加一下。
能否详细描述一下此功能和你的写法？

**Comment by EvanNotFound** [comment]
关于aplayer是因为网站使用了pjax，所以可能会有js加载问题，我下一个版本看看。
你可以尝试在 _config.redefine.yml 里面把pjax选项关闭再看看

**Comment by zhaosq11** [comment]
1、关于aplayer测试如下（不清楚是不是我写法有问题，我参考的是aplayer github上的写法）
![image](https://user-images.githubusercontent.com/95084791/219279175-29f0fa98-8d8c-4f94-876f-f8d1f3172377.png)
2、我写了一个简单的音乐界面   
这是正常访问看到的
![image](https://user-images.githubusercontent.com/95084791/219282925-13a81acc-92b3-4542-addc-8aac8262948c.png)
这是经过主题渲染过的
![image](https://user-images.githubusercontent.com/95084791/219283050-a14d0141-784f-4ae6-ab61-32165755c99c.png)
然后刷新变成这样，
![image](https://user-images.githubusercontent.com/95084791/219283195-0a96a46d-d46c-4b8a-a876-478223dd90a1.png)
具体想实现的效果就是一个页面是音乐页面，支持后台播放，音乐文件从本地加载。
![image](https://user-images.githubusercontent.com/95084791/219283511-a848d0e2-1ac4-4ebd-a4d7-8d112ee02511.png)
后端文件夹为一个music目录文件,用来放音乐文件
![image](https://user-images.githubusercontent.com/95084791/219283959-d858f945-bfe4-43e7-a0a9-8e752b6fa56b.png)
![image](https://user-images.githubusercontent.com/95084791/219284255-a43fe648-1b6d-4bb2-98a5-ce6acbc00909.png)
目前找了很多的hexo的demo,但是都是用的其他音乐软件生成的音乐链接，您做的demo目前在我看来所有的中，是好看简约清晰的，希望支持更多功能，感谢。
具体音乐的代码demo，我这有，但是不太清楚如何上传。

**Comment by EvanNotFound** [comment]
好的，有问题我再问你

**Comment by EvanNotFound** [comment]
如果方便的话，麻烦加我微信 `do-not-go-plzzz`，这样和你讨论方便一点

**Comment by EvanNotFound** [comment]
如需增加全站音乐播放器，请使用官方的 aplayer 

这里有其他人写的文档（虽然是next主题，但是操作步骤基本一致。我已经测试过了可行，全站可用）：https://asdfv1929.github.io/2018/05/26/next-add-music/

<img width="1512" alt="Screenshot 2023-02-22 at 8 41 37 PM" src="https://user-images.githubusercontent.com/68590232/220803305-477814cd-d268-483e-9c0b-dec759a2c87e.png">
<img width="948" alt="Screenshot 2023-02-22 at 8 42 58 PM" src="https://user-images.githubusercontent.com/68590232/220803451-4ea01093-e370-4229-8f0a-ba010e7e0695.png">

<img width="865" alt="Screenshot 2023-02-22 at 8 43 46 PM" src="https://user-images.githubusercontent.com/68590232/220803546-abf73667-738c-4bde-96a7-79b372e4f994.png">



<img width="249" alt="Screenshot 2023-02-22 at 8 42 47 PM" src="https://user-images.githubusercontent.com/68590232/220803416-fa9143b0-f116-4654-b8a4-08b7c7d2716b.png">

**Comment by EvanNotFound** [comment]
对于主题内置aplayer的话，我还要在考虑考虑这个功能是否必要

**Comment by EvanNotFound** [comment]
Redefine v1.1.4 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.4 查看

**Comment by Kemeow815** [comment]
> Redefine v1.1.4 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.4 查看

请问能否增加使用网易云这类的歌单播放？
