### ISSUE TITLE
[BUG]Uncaught ReferenceError: Odometer is not defined

### ISSUE THREAD

**Issue by liugt34** [EvanNotFound/hexo-theme-redefine#64]
就是代码clone下来之后，啥也没改，直接 hexo clean  && hexo serve

浏览器访问 http://localhost:4000 后出来控制台就就会输出这个错误，但是不影响网站运行

**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
清晰地描述，请提供
未作修改

**复现方法**
复现该 Bug 的步骤：

**截图**
如果可以，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/8056013/219288762-018f9f41-1f49-40a6-b6d3-5c87999988f0.png)

![image](https://user-images.githubusercontent.com/8056013/219289351-37f4bb0c-62cd-4b86-ae16-a9cb393fed70.png)

**Comment by EvanNotFound** [comment]
你好，我已经在dev分支修复了这个bug，所以请耐心等待下一版本

**Comment by EvanNotFound** [comment]
Redefine v1.1.2 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.2 查看
