### ISSUE TITLE
[功能建议] 文章日期可以选择只显示日期不显示时间以及增加文章更新时间的建议

### ISSUE THREAD

**Issue by dzvision** [EvanNotFound/hexo-theme-redefine#65]
# 1. 文章日期含时间显示问题
**功能概述**
当我的文章markdown只是使用
```
date: 2023-08-24
```
的方式时，他会显示2023-08-24 00:00:00

**期望显示**
我期望是他可以只显示2023-08-24.
例如从_config.redefine文件修改，或者自动识别md文档，当有时间的时候有，没有时间的时候就没有。

**图片描述**
![Datetime](https://user-images.githubusercontent.com/5590839/219318325-0d4a4060-5a8d-4abf-aa01-095ed2f95172.png)

# 2. 文章日期更新显示
**功能概述**
希望可以增加文章更新的时间。无论是在文章上面展示还是在下面展示，都行，有就可以了。

```
date: 2023-01-24
updated: 2023-02-16
```

**图片描述**
无图

**Comment by EvanNotFound** [comment]
好的，这就加

**Comment by EvanNotFound** [comment]
新版本文章日期更新显示不需要特意写 `updated`，主题会自动识别markdown信息

**Comment by EvanNotFound** [comment]
Redefine v1.1.2 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.2 查看
