### ISSUE TITLE
[BUG]Tabs分栏里代码块显示异常

### ISSUE THREAD

**Issue by jkoor** [EvanNotFound/hexo-theme-redefine#69]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
在Tabs分栏里插入代码显示异常，代码块上边框变短
![image](https://user-images.githubusercontent.com/31055463/220060760-3749dda5-b88c-4173-984c-95ebb7570a53.png)

**复现方法**
在Tabs分栏里插入代码

**预期结果**
![image](https://user-images.githubusercontent.com/31055463/220060934-6ee95c48-1fb6-48b8-b8ac-4139dab3bdbf.png)

**截图**
如上

**电脑（请填写以下信息）：**
 - 操作系统：windows
 - 浏览器 chrome
 - 版本 102

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
下一版本修复

**Comment by EvanNotFound** [comment]
已经在 Dev 分支修复，请等待下一版本

**Comment by EvanNotFound** [comment]
Redefine v1.1.3 已修复此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.3 查看
