### ISSUE TITLE
[功能建议] 建议升级 Waline 版本

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#70]
Waline 现已更新到 2.14.7，罗老师能升级一下 Waline 的静态资源吗 QwQ

**Comment by EvanNotFound** [comment]
好的，下一版本

**Comment by EvanNotFound** [comment]
Redefine v1.1.3 已更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.3 查看
