### ISSUE TITLE
[BUG] 代码缩进问题

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#72]
四格缩进，在网页中显示的却像八格一样，悲
![image](https://user-images.githubusercontent.com/117651674/220640744-ae00f194-865b-4b6f-9d85-ccd0c28bcfd8.png)
奇妙的是，也有正常的：
![image](https://user-images.githubusercontent.com/117651674/220640915-ea3da8ee-5d89-49c6-a4db-6a8978142338.png)
求罗老师解决qwq

**Comment by EvanNotFound** [comment]
这，请发一下markdown的写法，我去看看

**Comment by ncwzdlsd** [comment]
> 这，请发一下markdown的写法，我去看看

Markdown 的写法就是正常的
```cpp
```

我用的是 Typora 编辑器，在本地可以正常显示缩进，并且离谱的是我复制网页中的代码粘贴到本地 IDE 中也是正常的四格缩进，就是到了网站上就变成八格了（悲）并且实测用别的主题是正常的缩进

**Comment by EvanNotFound** [comment]
发个网站链接

**Comment by EvanNotFound** [comment]
好了，我改了一下 `tab-size`直接解决了
