### ISSUE TITLE
[BUG] Waline评论不显示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#73]
Waline 评论不显示，已正确配置且域名从 `vercel` 原生域名已 `CNAME` 到个人域名排除被q的情况，其他主题仍可正常显示

**Comment by EvanNotFound** [comment]
请提供详细配置信息

**Comment by EvanNotFound** [comment]
抱歉，是我更新的时候手贱在cdn端把 `waline.js` 删了，现在已经恢复了
