### ISSUE TITLE
[BUG] 分类页文章数量显示错误

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#79]
进入到一个分类界面后，如果该分类下的某一年份的文章超过 $10$ 篇，只会显示 `2023 [10]` 而不显示实际篇数

**Comment by EvanNotFound** [comment]
请提供具体信息

**Comment by ncwzdlsd** [comment]
就是如果在一年里写了很多篇同一分类下的文章，会显示
![image](https://user-images.githubusercontent.com/117651674/222431544-f1e89d5e-2d47-4270-a276-1646e4bb7e14.png)
而不是实际该分类下该年份的实际文章数，比如 `2023[14]`

**Comment by EvanNotFound** [comment]
<img width="1512" alt="Screenshot 2023-03-08 at 10 31 04 AM" src="https://user-images.githubusercontent.com/68590232/223756188-abceb339-727d-4787-a249-44be29e4772b.png">

**Comment by ncwzdlsd** [comment]
> <img alt="Screenshot 2023-03-08 at 10 31 04 AM" width="1512" src="https://user-images.githubusercontent.com/68590232/223756188-abceb339-727d-4787-a249-44be29e4772b.png">
> 
> 抱歉，但是我没遇到啊

您这个好像是归档页面，我指的是分类页面 `categories`😭😭😭😖😖😖

**Comment by EvanNotFound** [comment]
我的问题，抱歉抱歉

**Comment by EvanNotFound** [comment]
但是分类页面没有年份显示啊

<img width="1512" alt="Screenshot 2023-03-09 at 11 28 14 AM" src="https://user-images.githubusercontent.com/68590232/224088512-d155d838-b4c1-4c4c-9574-e3aac5c9d6f9.png">

**Comment by ncwzdlsd** [comment]
> 但是分类页面没有年份显示啊
> 
> <img alt="Screenshot 2023-03-09 at 11 28 14 AM" width="1512" src="https://user-images.githubusercontent.com/68590232/224088512-d155d838-b4c1-4c4c-9574-e3aac5c9d6f9.png">

哦哦我没有开多级分类，如果是单级分类就会有年份显示的，比如这样：
![image](https://user-images.githubusercontent.com/117651674/224099737-431c1c9b-a54b-42d3-bd0e-d4eb729f3e74.png)

**Comment by EvanNotFound** [comment]
好的我看看

**Comment by EvanNotFound** [comment]
本功能不是主题问题，请查看：https://github.com/hexojs/hexo-generator-category

只要在 Hexo 站点配置文件写上

```yaml
category_generator:
  per_page: 0
  order_by: -date
```

就可以
