### ISSUE TITLE
[BUG] 折叠块异常显示

### ISSUE THREAD

**Issue by ncwzdlsd** [EvanNotFound/hexo-theme-redefine#80]
居然显示了 HTML 的语法
![image](https://user-images.githubusercontent.com/117651674/221812314-898e95b2-e9f5-4332-a505-275284b6b628.png)
用的就是文档中的代码，`关于` 页面的 `front=matter` 的如下：
![image](https://user-images.githubusercontent.com/117651674/221812485-de226a1e-de86-47f3-a8dd-ece867f8be78.png)

**Comment by EvanNotFound** [comment]
Redefine v1.1.4 已修复此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.4 查看
