### ISSUE TITLE
[BUG] 代码块使用simple样式后，折叠显示异常

### ISSUE THREAD

**Issue by jkoor** [EvanNotFound/hexo-theme-redefine#82]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
1. 代码块使用simple样式后，折叠显示异常
![image](https://user-images.githubusercontent.com/31055463/222341533-f3209dd5-d0c3-4139-9518-3e7d0fb0db3b.png)
2. 这是一个建议，感觉代码块的标题与代码间距有点奇怪，左右既没有和行号对齐，也没和代码对齐，上下距离代码间距有点近了
![image](https://user-images.githubusercontent.com/31055463/222341856-28028fcd-71e4-4a74-80cb-a5f39a2de882.png)

**复现方法**
折叠代码块

**预期结果**
在分栏里折叠是正常的，可能是因为前后背景同色看不出来
![image](https://user-images.githubusercontent.com/31055463/222342654-a39380ea-4f0f-40c5-a014-6fb1814ef13d.png)

**截图**
已附上

**电脑（请填写以下信息）：**
 - 操作系统：Windows 11
 - 浏览器 Chrome
 - 版本 108

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by EvanNotFound** [comment]
好的。下一版本修复

**Comment by EvanNotFound** [comment]
Redefine v1.1.5 已修复此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.1.5 查看
