### ISSUE TITLE
[BUG] 文章头图thumbnail处理相对路径问题

### ISSUE THREAD

**Issue by attson** [EvanNotFound/hexo-theme-redefine#87]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

文章头图thumbnail无法正确处理相对路径

**复现方法**
复现该 Bug 的步骤：

// 我的图片会在 site://p/asus-ac68u-shadowsocks/bg.jpeg 下（markown内的图片也是在这里）

_post  目录层级

```
├── asus-ac68u-shadowsocks
 │   └── bg.jpeg
├── asus-ac68u-shadowsocks.md

```

文章头图使用相对地址
```
---
...
thumbnail: "p/asus-ac68u-shadowsocks/bg.jpeg"
---
```
时，在首页列表能正确展示图片，文章详情图片错误

```
---
...
thumbnail: "p/asus-ac68u-shadowsocks/bg.jpeg"
---
```

时，在文章详情图片能正确展示图片，首页列表图片错误

**预期结果**
该功能本来应该是怎么样的

在两块都能正确处理相对路径

**截图**
如果可以，请添加截图以帮助解释您的问题。

![image](https://user-images.githubusercontent.com/119783163/222885170-b5281b17-7b00-4b65-b8f1-c1a05da74963.png)

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]
Chrome macOS

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

hexo: 6.3.0
redefine: 1.1.6

**Comment by EvanNotFound** [comment]
Redefine v1.2.0 已修复/更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.2.0 查看
