### ISSUE TITLE
[Question] 在其他页面引用分页不起作用

### ISSUE THREAD

**Issue by Amber916Young** [EvanNotFound/hexo-theme-redefine#89]
在其他页面引用分页不起作用呢？
<img width="1231" alt="Screenshot 2023-03-05 at 01 32 32" src="https://user-images.githubusercontent.com/57694784/222936782-e535caad-a55a-4429-816b-b9c4ffe4f4e0.png">

**Comment by EvanNotFound** [comment]
什么意思？请详细描述一下

**Comment by Amber916Young** [comment]
你好，我另外创建了文章列表的页面，我想引用paginator，但是这个页面会全部列出文章。

**Comment by EvanNotFound** [comment]
无详细信息，本 Issue 关闭。如有问题，欢迎 Reopen
