### ISSUE TITLE
[功能建议] 选择决定在head的meta中是否添加图片

### ISSUE THREAD

**Issue by Fdslk** [EvanNotFound/hexo-theme-redefine#91]
**功能概述**
不知道咱们现在配置中有没有可以去除在html中的meta中设置图片，因为在微信中分享的时候，如果该图片的域名没有备份或者没有加入白名单的时候，就无法显示，所以我们能不能加一个选项，选择决定在head的meta中是否添加图片？
**图片描述**
![image](https://user-images.githubusercontent.com/6279298/222951680-d2e3c06b-252e-453e-98a7-a28a323c9e29.png)

<img width="603" alt="image" src="https://user-images.githubusercontent.com/6279298/222951636-dd7e001e-f0a9-4b36-acbd-8080c0226c36.png">

**Comment by EvanNotFound** [comment]
已在dev分支更新，请等待下一版本

**Comment by EvanNotFound** [comment]
Redefine v1.2.0 已修复/更新此功能，欢迎前往 https://github.com/EvanNotFound/hexo-theme-redefine/releases/tag/v1.2.0 查看

**Comment by Fdslk** [comment]
666
